// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dto

import (
	"context"
	"english-study/internal/model/bean"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newArticleWord(db *gorm.DB, opts ...gen.DOOption) articleWord {
	_articleWord := articleWord{}

	_articleWord.articleWordDo.UseDB(db, opts...)
	_articleWord.articleWordDo.UseModel(&bean.ArticleWord{})

	tableName := _articleWord.articleWordDo.TableName()
	_articleWord.ALL = field.NewAsterisk(tableName)
	_articleWord.ID = field.NewUint(tableName, "id")
	_articleWord.ArticleID = field.NewUint(tableName, "article_id")
	_articleWord.UserID = field.NewUint(tableName, "user_id")
	_articleWord.WordID = field.NewUint(tableName, "word_id")
	_articleWord.WordType = field.NewInt(tableName, "word_type")
	_articleWord.WordText = field.NewString(tableName, "word_text")

	_articleWord.fillFieldMap()

	return _articleWord
}

type articleWord struct {
	articleWordDo

	ALL       field.Asterisk
	ID        field.Uint
	ArticleID field.Uint
	UserID    field.Uint
	WordID    field.Uint
	WordType  field.Int
	WordText  field.String

	fieldMap map[string]field.Expr
}

func (a articleWord) Table(newTableName string) *articleWord {
	a.articleWordDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a articleWord) As(alias string) *articleWord {
	a.articleWordDo.DO = *(a.articleWordDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *articleWord) updateTableName(table string) *articleWord {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint(table, "id")
	a.ArticleID = field.NewUint(table, "article_id")
	a.UserID = field.NewUint(table, "user_id")
	a.WordID = field.NewUint(table, "word_id")
	a.WordType = field.NewInt(table, "word_type")
	a.WordText = field.NewString(table, "word_text")

	a.fillFieldMap()

	return a
}

func (a *articleWord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *articleWord) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 6)
	a.fieldMap["id"] = a.ID
	a.fieldMap["article_id"] = a.ArticleID
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["word_id"] = a.WordID
	a.fieldMap["word_type"] = a.WordType
	a.fieldMap["word_text"] = a.WordText
}

func (a articleWord) clone(db *gorm.DB) articleWord {
	a.articleWordDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a articleWord) replaceDB(db *gorm.DB) articleWord {
	a.articleWordDo.ReplaceDB(db)
	return a
}

type articleWordDo struct{ gen.DO }

type IArticleWordDo interface {
	gen.SubQuery
	Debug() IArticleWordDo
	WithContext(ctx context.Context) IArticleWordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IArticleWordDo
	WriteDB() IArticleWordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IArticleWordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IArticleWordDo
	Not(conds ...gen.Condition) IArticleWordDo
	Or(conds ...gen.Condition) IArticleWordDo
	Select(conds ...field.Expr) IArticleWordDo
	Where(conds ...gen.Condition) IArticleWordDo
	Order(conds ...field.Expr) IArticleWordDo
	Distinct(cols ...field.Expr) IArticleWordDo
	Omit(cols ...field.Expr) IArticleWordDo
	Join(table schema.Tabler, on ...field.Expr) IArticleWordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IArticleWordDo
	RightJoin(table schema.Tabler, on ...field.Expr) IArticleWordDo
	Group(cols ...field.Expr) IArticleWordDo
	Having(conds ...gen.Condition) IArticleWordDo
	Limit(limit int) IArticleWordDo
	Offset(offset int) IArticleWordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IArticleWordDo
	Unscoped() IArticleWordDo
	Create(values ...*bean.ArticleWord) error
	CreateInBatches(values []*bean.ArticleWord, batchSize int) error
	Save(values ...*bean.ArticleWord) error
	First() (*bean.ArticleWord, error)
	Take() (*bean.ArticleWord, error)
	Last() (*bean.ArticleWord, error)
	Find() ([]*bean.ArticleWord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*bean.ArticleWord, err error)
	FindInBatches(result *[]*bean.ArticleWord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*bean.ArticleWord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IArticleWordDo
	Assign(attrs ...field.AssignExpr) IArticleWordDo
	Joins(fields ...field.RelationField) IArticleWordDo
	Preload(fields ...field.RelationField) IArticleWordDo
	FirstOrInit() (*bean.ArticleWord, error)
	FirstOrCreate() (*bean.ArticleWord, error)
	FindByPage(offset int, limit int) (result []*bean.ArticleWord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IArticleWordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a articleWordDo) Debug() IArticleWordDo {
	return a.withDO(a.DO.Debug())
}

func (a articleWordDo) WithContext(ctx context.Context) IArticleWordDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a articleWordDo) ReadDB() IArticleWordDo {
	return a.Clauses(dbresolver.Read)
}

func (a articleWordDo) WriteDB() IArticleWordDo {
	return a.Clauses(dbresolver.Write)
}

func (a articleWordDo) Session(config *gorm.Session) IArticleWordDo {
	return a.withDO(a.DO.Session(config))
}

func (a articleWordDo) Clauses(conds ...clause.Expression) IArticleWordDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a articleWordDo) Returning(value interface{}, columns ...string) IArticleWordDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a articleWordDo) Not(conds ...gen.Condition) IArticleWordDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a articleWordDo) Or(conds ...gen.Condition) IArticleWordDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a articleWordDo) Select(conds ...field.Expr) IArticleWordDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a articleWordDo) Where(conds ...gen.Condition) IArticleWordDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a articleWordDo) Order(conds ...field.Expr) IArticleWordDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a articleWordDo) Distinct(cols ...field.Expr) IArticleWordDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a articleWordDo) Omit(cols ...field.Expr) IArticleWordDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a articleWordDo) Join(table schema.Tabler, on ...field.Expr) IArticleWordDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a articleWordDo) LeftJoin(table schema.Tabler, on ...field.Expr) IArticleWordDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a articleWordDo) RightJoin(table schema.Tabler, on ...field.Expr) IArticleWordDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a articleWordDo) Group(cols ...field.Expr) IArticleWordDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a articleWordDo) Having(conds ...gen.Condition) IArticleWordDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a articleWordDo) Limit(limit int) IArticleWordDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a articleWordDo) Offset(offset int) IArticleWordDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a articleWordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IArticleWordDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a articleWordDo) Unscoped() IArticleWordDo {
	return a.withDO(a.DO.Unscoped())
}

func (a articleWordDo) Create(values ...*bean.ArticleWord) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a articleWordDo) CreateInBatches(values []*bean.ArticleWord, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a articleWordDo) Save(values ...*bean.ArticleWord) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a articleWordDo) First() (*bean.ArticleWord, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*bean.ArticleWord), nil
	}
}

func (a articleWordDo) Take() (*bean.ArticleWord, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*bean.ArticleWord), nil
	}
}

func (a articleWordDo) Last() (*bean.ArticleWord, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*bean.ArticleWord), nil
	}
}

func (a articleWordDo) Find() ([]*bean.ArticleWord, error) {
	result, err := a.DO.Find()
	return result.([]*bean.ArticleWord), err
}

func (a articleWordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*bean.ArticleWord, err error) {
	buf := make([]*bean.ArticleWord, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a articleWordDo) FindInBatches(result *[]*bean.ArticleWord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a articleWordDo) Attrs(attrs ...field.AssignExpr) IArticleWordDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a articleWordDo) Assign(attrs ...field.AssignExpr) IArticleWordDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a articleWordDo) Joins(fields ...field.RelationField) IArticleWordDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a articleWordDo) Preload(fields ...field.RelationField) IArticleWordDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a articleWordDo) FirstOrInit() (*bean.ArticleWord, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*bean.ArticleWord), nil
	}
}

func (a articleWordDo) FirstOrCreate() (*bean.ArticleWord, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*bean.ArticleWord), nil
	}
}

func (a articleWordDo) FindByPage(offset int, limit int) (result []*bean.ArticleWord, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a articleWordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a articleWordDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a articleWordDo) Delete(models ...*bean.ArticleWord) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *articleWordDo) withDO(do gen.Dao) *articleWordDo {
	a.DO = *do.(*gen.DO)
	return a
}
