// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dto

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:         db,
		ImportTask: newImportTask(db, opts...),
		StarDict:   newStarDict(db, opts...),
		Tag:        newTag(db, opts...),
		User:       newUser(db, opts...),
		Word:       newWord(db, opts...),
		WordPhrase: newWordPhrase(db, opts...),
		WordPos:    newWordPos(db, opts...),
		WordStatus: newWordStatus(db, opts...),
		WordTag:    newWordTag(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	ImportTask importTask
	StarDict   starDict
	Tag        tag
	User       user
	Word       word
	WordPhrase wordPhrase
	WordPos    wordPos
	WordStatus wordStatus
	WordTag    wordTag
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:         db,
		ImportTask: q.ImportTask.clone(db),
		StarDict:   q.StarDict.clone(db),
		Tag:        q.Tag.clone(db),
		User:       q.User.clone(db),
		Word:       q.Word.clone(db),
		WordPhrase: q.WordPhrase.clone(db),
		WordPos:    q.WordPos.clone(db),
		WordStatus: q.WordStatus.clone(db),
		WordTag:    q.WordTag.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:         db,
		ImportTask: q.ImportTask.replaceDB(db),
		StarDict:   q.StarDict.replaceDB(db),
		Tag:        q.Tag.replaceDB(db),
		User:       q.User.replaceDB(db),
		Word:       q.Word.replaceDB(db),
		WordPhrase: q.WordPhrase.replaceDB(db),
		WordPos:    q.WordPos.replaceDB(db),
		WordStatus: q.WordStatus.replaceDB(db),
		WordTag:    q.WordTag.replaceDB(db),
	}
}

type queryCtx struct {
	ImportTask IImportTaskDo
	StarDict   IStarDictDo
	Tag        ITagDo
	User       IUserDo
	Word       IWordDo
	WordPhrase IWordPhraseDo
	WordPos    IWordPosDo
	WordStatus IWordStatusDo
	WordTag    IWordTagDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		ImportTask: q.ImportTask.WithContext(ctx),
		StarDict:   q.StarDict.WithContext(ctx),
		Tag:        q.Tag.WithContext(ctx),
		User:       q.User.WithContext(ctx),
		Word:       q.Word.WithContext(ctx),
		WordPhrase: q.WordPhrase.WithContext(ctx),
		WordPos:    q.WordPos.WithContext(ctx),
		WordStatus: q.WordStatus.WithContext(ctx),
		WordTag:    q.WordTag.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
