// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dto

import (
	"context"
	"english-study/internal/model/bean"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newImportTask(db *gorm.DB, opts ...gen.DOOption) importTask {
	_importTask := importTask{}

	_importTask.importTaskDo.UseDB(db, opts...)
	_importTask.importTaskDo.UseModel(&bean.ImportTask{})

	tableName := _importTask.importTaskDo.TableName()
	_importTask.ALL = field.NewAsterisk(tableName)
	_importTask.ID = field.NewUint(tableName, "id")
	_importTask.UserID = field.NewUint(tableName, "user_id")
	_importTask.FileName = field.NewString(tableName, "file_name")
	_importTask.Status = field.NewInt(tableName, "status")
	_importTask.Total = field.NewInt(tableName, "total")
	_importTask.Current = field.NewInt(tableName, "current")
	_importTask.CurrentWord = field.NewString(tableName, "current_word")
	_importTask.SuccessCount = field.NewInt(tableName, "success_count")
	_importTask.FailCount = field.NewInt(tableName, "fail_count")
	_importTask.FailWords = field.NewString(tableName, "fail_words")
	_importTask.CreatedAt = field.NewTime(tableName, "created_at")
	_importTask.UpdatedAt = field.NewTime(tableName, "updated_at")

	_importTask.fillFieldMap()

	return _importTask
}

type importTask struct {
	importTaskDo

	ALL          field.Asterisk
	ID           field.Uint
	UserID       field.Uint
	FileName     field.String
	Status       field.Int
	Total        field.Int
	Current      field.Int
	CurrentWord  field.String
	SuccessCount field.Int
	FailCount    field.Int
	FailWords    field.String
	CreatedAt    field.Time
	UpdatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (i importTask) Table(newTableName string) *importTask {
	i.importTaskDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i importTask) As(alias string) *importTask {
	i.importTaskDo.DO = *(i.importTaskDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *importTask) updateTableName(table string) *importTask {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewUint(table, "id")
	i.UserID = field.NewUint(table, "user_id")
	i.FileName = field.NewString(table, "file_name")
	i.Status = field.NewInt(table, "status")
	i.Total = field.NewInt(table, "total")
	i.Current = field.NewInt(table, "current")
	i.CurrentWord = field.NewString(table, "current_word")
	i.SuccessCount = field.NewInt(table, "success_count")
	i.FailCount = field.NewInt(table, "fail_count")
	i.FailWords = field.NewString(table, "fail_words")
	i.CreatedAt = field.NewTime(table, "created_at")
	i.UpdatedAt = field.NewTime(table, "updated_at")

	i.fillFieldMap()

	return i
}

func (i *importTask) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *importTask) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 12)
	i.fieldMap["id"] = i.ID
	i.fieldMap["user_id"] = i.UserID
	i.fieldMap["file_name"] = i.FileName
	i.fieldMap["status"] = i.Status
	i.fieldMap["total"] = i.Total
	i.fieldMap["current"] = i.Current
	i.fieldMap["current_word"] = i.CurrentWord
	i.fieldMap["success_count"] = i.SuccessCount
	i.fieldMap["fail_count"] = i.FailCount
	i.fieldMap["fail_words"] = i.FailWords
	i.fieldMap["created_at"] = i.CreatedAt
	i.fieldMap["updated_at"] = i.UpdatedAt
}

func (i importTask) clone(db *gorm.DB) importTask {
	i.importTaskDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i importTask) replaceDB(db *gorm.DB) importTask {
	i.importTaskDo.ReplaceDB(db)
	return i
}

type importTaskDo struct{ gen.DO }

type IImportTaskDo interface {
	gen.SubQuery
	Debug() IImportTaskDo
	WithContext(ctx context.Context) IImportTaskDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IImportTaskDo
	WriteDB() IImportTaskDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IImportTaskDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IImportTaskDo
	Not(conds ...gen.Condition) IImportTaskDo
	Or(conds ...gen.Condition) IImportTaskDo
	Select(conds ...field.Expr) IImportTaskDo
	Where(conds ...gen.Condition) IImportTaskDo
	Order(conds ...field.Expr) IImportTaskDo
	Distinct(cols ...field.Expr) IImportTaskDo
	Omit(cols ...field.Expr) IImportTaskDo
	Join(table schema.Tabler, on ...field.Expr) IImportTaskDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IImportTaskDo
	RightJoin(table schema.Tabler, on ...field.Expr) IImportTaskDo
	Group(cols ...field.Expr) IImportTaskDo
	Having(conds ...gen.Condition) IImportTaskDo
	Limit(limit int) IImportTaskDo
	Offset(offset int) IImportTaskDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IImportTaskDo
	Unscoped() IImportTaskDo
	Create(values ...*bean.ImportTask) error
	CreateInBatches(values []*bean.ImportTask, batchSize int) error
	Save(values ...*bean.ImportTask) error
	First() (*bean.ImportTask, error)
	Take() (*bean.ImportTask, error)
	Last() (*bean.ImportTask, error)
	Find() ([]*bean.ImportTask, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*bean.ImportTask, err error)
	FindInBatches(result *[]*bean.ImportTask, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*bean.ImportTask) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IImportTaskDo
	Assign(attrs ...field.AssignExpr) IImportTaskDo
	Joins(fields ...field.RelationField) IImportTaskDo
	Preload(fields ...field.RelationField) IImportTaskDo
	FirstOrInit() (*bean.ImportTask, error)
	FirstOrCreate() (*bean.ImportTask, error)
	FindByPage(offset int, limit int) (result []*bean.ImportTask, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IImportTaskDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i importTaskDo) Debug() IImportTaskDo {
	return i.withDO(i.DO.Debug())
}

func (i importTaskDo) WithContext(ctx context.Context) IImportTaskDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i importTaskDo) ReadDB() IImportTaskDo {
	return i.Clauses(dbresolver.Read)
}

func (i importTaskDo) WriteDB() IImportTaskDo {
	return i.Clauses(dbresolver.Write)
}

func (i importTaskDo) Session(config *gorm.Session) IImportTaskDo {
	return i.withDO(i.DO.Session(config))
}

func (i importTaskDo) Clauses(conds ...clause.Expression) IImportTaskDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i importTaskDo) Returning(value interface{}, columns ...string) IImportTaskDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i importTaskDo) Not(conds ...gen.Condition) IImportTaskDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i importTaskDo) Or(conds ...gen.Condition) IImportTaskDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i importTaskDo) Select(conds ...field.Expr) IImportTaskDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i importTaskDo) Where(conds ...gen.Condition) IImportTaskDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i importTaskDo) Order(conds ...field.Expr) IImportTaskDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i importTaskDo) Distinct(cols ...field.Expr) IImportTaskDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i importTaskDo) Omit(cols ...field.Expr) IImportTaskDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i importTaskDo) Join(table schema.Tabler, on ...field.Expr) IImportTaskDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i importTaskDo) LeftJoin(table schema.Tabler, on ...field.Expr) IImportTaskDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i importTaskDo) RightJoin(table schema.Tabler, on ...field.Expr) IImportTaskDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i importTaskDo) Group(cols ...field.Expr) IImportTaskDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i importTaskDo) Having(conds ...gen.Condition) IImportTaskDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i importTaskDo) Limit(limit int) IImportTaskDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i importTaskDo) Offset(offset int) IImportTaskDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i importTaskDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IImportTaskDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i importTaskDo) Unscoped() IImportTaskDo {
	return i.withDO(i.DO.Unscoped())
}

func (i importTaskDo) Create(values ...*bean.ImportTask) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i importTaskDo) CreateInBatches(values []*bean.ImportTask, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i importTaskDo) Save(values ...*bean.ImportTask) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i importTaskDo) First() (*bean.ImportTask, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*bean.ImportTask), nil
	}
}

func (i importTaskDo) Take() (*bean.ImportTask, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*bean.ImportTask), nil
	}
}

func (i importTaskDo) Last() (*bean.ImportTask, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*bean.ImportTask), nil
	}
}

func (i importTaskDo) Find() ([]*bean.ImportTask, error) {
	result, err := i.DO.Find()
	return result.([]*bean.ImportTask), err
}

func (i importTaskDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*bean.ImportTask, err error) {
	buf := make([]*bean.ImportTask, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i importTaskDo) FindInBatches(result *[]*bean.ImportTask, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i importTaskDo) Attrs(attrs ...field.AssignExpr) IImportTaskDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i importTaskDo) Assign(attrs ...field.AssignExpr) IImportTaskDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i importTaskDo) Joins(fields ...field.RelationField) IImportTaskDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i importTaskDo) Preload(fields ...field.RelationField) IImportTaskDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i importTaskDo) FirstOrInit() (*bean.ImportTask, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*bean.ImportTask), nil
	}
}

func (i importTaskDo) FirstOrCreate() (*bean.ImportTask, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*bean.ImportTask), nil
	}
}

func (i importTaskDo) FindByPage(offset int, limit int) (result []*bean.ImportTask, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i importTaskDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i importTaskDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i importTaskDo) Delete(models ...*bean.ImportTask) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *importTaskDo) withDO(do gen.Dao) *importTaskDo {
	i.DO = *do.(*gen.DO)
	return i
}
