// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dto

import (
	"context"
	"english-study/internal/model/bean"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newStarDict(db *gorm.DB, opts ...gen.DOOption) starDict {
	_starDict := starDict{}

	_starDict.starDictDo.UseDB(db, opts...)
	_starDict.starDictDo.UseModel(&bean.StarDict{})

	tableName := _starDict.starDictDo.TableName()
	_starDict.ALL = field.NewAsterisk(tableName)
	_starDict.ID = field.NewUint(tableName, "id")
	_starDict.Word = field.NewString(tableName, "word")
	_starDict.Sw = field.NewString(tableName, "sw")
	_starDict.Phonetic = field.NewString(tableName, "phonetic")
	_starDict.Definition = field.NewString(tableName, "definition")
	_starDict.Translation = field.NewString(tableName, "translation")
	_starDict.Pos = field.NewString(tableName, "pos")
	_starDict.Collins = field.NewInt(tableName, "collins")
	_starDict.Oxford = field.NewInt(tableName, "oxford")
	_starDict.Tag = field.NewString(tableName, "tag")
	_starDict.Bnc = field.NewInt(tableName, "bnc")
	_starDict.Frq = field.NewInt(tableName, "frq")
	_starDict.Exchange = field.NewString(tableName, "exchange")
	_starDict.Detail = field.NewString(tableName, "detail")
	_starDict.Audio = field.NewString(tableName, "audio")
	_starDict.CreatedAt = field.NewTime(tableName, "created_at")
	_starDict.UpdatedAt = field.NewTime(tableName, "updated_at")
	_starDict.DeletedAt = field.NewField(tableName, "deleted_at")

	_starDict.fillFieldMap()

	return _starDict
}

type starDict struct {
	starDictDo

	ALL         field.Asterisk
	ID          field.Uint
	Word        field.String
	Sw          field.String
	Phonetic    field.String
	Definition  field.String
	Translation field.String
	Pos         field.String
	Collins     field.Int
	Oxford      field.Int
	Tag         field.String
	Bnc         field.Int
	Frq         field.Int
	Exchange    field.String
	Detail      field.String
	Audio       field.String
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field

	fieldMap map[string]field.Expr
}

func (s starDict) Table(newTableName string) *starDict {
	s.starDictDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s starDict) As(alias string) *starDict {
	s.starDictDo.DO = *(s.starDictDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *starDict) updateTableName(table string) *starDict {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewUint(table, "id")
	s.Word = field.NewString(table, "word")
	s.Sw = field.NewString(table, "sw")
	s.Phonetic = field.NewString(table, "phonetic")
	s.Definition = field.NewString(table, "definition")
	s.Translation = field.NewString(table, "translation")
	s.Pos = field.NewString(table, "pos")
	s.Collins = field.NewInt(table, "collins")
	s.Oxford = field.NewInt(table, "oxford")
	s.Tag = field.NewString(table, "tag")
	s.Bnc = field.NewInt(table, "bnc")
	s.Frq = field.NewInt(table, "frq")
	s.Exchange = field.NewString(table, "exchange")
	s.Detail = field.NewString(table, "detail")
	s.Audio = field.NewString(table, "audio")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")

	s.fillFieldMap()

	return s
}

func (s *starDict) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *starDict) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 18)
	s.fieldMap["id"] = s.ID
	s.fieldMap["word"] = s.Word
	s.fieldMap["sw"] = s.Sw
	s.fieldMap["phonetic"] = s.Phonetic
	s.fieldMap["definition"] = s.Definition
	s.fieldMap["translation"] = s.Translation
	s.fieldMap["pos"] = s.Pos
	s.fieldMap["collins"] = s.Collins
	s.fieldMap["oxford"] = s.Oxford
	s.fieldMap["tag"] = s.Tag
	s.fieldMap["bnc"] = s.Bnc
	s.fieldMap["frq"] = s.Frq
	s.fieldMap["exchange"] = s.Exchange
	s.fieldMap["detail"] = s.Detail
	s.fieldMap["audio"] = s.Audio
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
}

func (s starDict) clone(db *gorm.DB) starDict {
	s.starDictDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s starDict) replaceDB(db *gorm.DB) starDict {
	s.starDictDo.ReplaceDB(db)
	return s
}

type starDictDo struct{ gen.DO }

type IStarDictDo interface {
	gen.SubQuery
	Debug() IStarDictDo
	WithContext(ctx context.Context) IStarDictDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IStarDictDo
	WriteDB() IStarDictDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IStarDictDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IStarDictDo
	Not(conds ...gen.Condition) IStarDictDo
	Or(conds ...gen.Condition) IStarDictDo
	Select(conds ...field.Expr) IStarDictDo
	Where(conds ...gen.Condition) IStarDictDo
	Order(conds ...field.Expr) IStarDictDo
	Distinct(cols ...field.Expr) IStarDictDo
	Omit(cols ...field.Expr) IStarDictDo
	Join(table schema.Tabler, on ...field.Expr) IStarDictDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IStarDictDo
	RightJoin(table schema.Tabler, on ...field.Expr) IStarDictDo
	Group(cols ...field.Expr) IStarDictDo
	Having(conds ...gen.Condition) IStarDictDo
	Limit(limit int) IStarDictDo
	Offset(offset int) IStarDictDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IStarDictDo
	Unscoped() IStarDictDo
	Create(values ...*bean.StarDict) error
	CreateInBatches(values []*bean.StarDict, batchSize int) error
	Save(values ...*bean.StarDict) error
	First() (*bean.StarDict, error)
	Take() (*bean.StarDict, error)
	Last() (*bean.StarDict, error)
	Find() ([]*bean.StarDict, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*bean.StarDict, err error)
	FindInBatches(result *[]*bean.StarDict, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*bean.StarDict) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IStarDictDo
	Assign(attrs ...field.AssignExpr) IStarDictDo
	Joins(fields ...field.RelationField) IStarDictDo
	Preload(fields ...field.RelationField) IStarDictDo
	FirstOrInit() (*bean.StarDict, error)
	FirstOrCreate() (*bean.StarDict, error)
	FindByPage(offset int, limit int) (result []*bean.StarDict, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IStarDictDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s starDictDo) Debug() IStarDictDo {
	return s.withDO(s.DO.Debug())
}

func (s starDictDo) WithContext(ctx context.Context) IStarDictDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s starDictDo) ReadDB() IStarDictDo {
	return s.Clauses(dbresolver.Read)
}

func (s starDictDo) WriteDB() IStarDictDo {
	return s.Clauses(dbresolver.Write)
}

func (s starDictDo) Session(config *gorm.Session) IStarDictDo {
	return s.withDO(s.DO.Session(config))
}

func (s starDictDo) Clauses(conds ...clause.Expression) IStarDictDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s starDictDo) Returning(value interface{}, columns ...string) IStarDictDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s starDictDo) Not(conds ...gen.Condition) IStarDictDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s starDictDo) Or(conds ...gen.Condition) IStarDictDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s starDictDo) Select(conds ...field.Expr) IStarDictDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s starDictDo) Where(conds ...gen.Condition) IStarDictDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s starDictDo) Order(conds ...field.Expr) IStarDictDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s starDictDo) Distinct(cols ...field.Expr) IStarDictDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s starDictDo) Omit(cols ...field.Expr) IStarDictDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s starDictDo) Join(table schema.Tabler, on ...field.Expr) IStarDictDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s starDictDo) LeftJoin(table schema.Tabler, on ...field.Expr) IStarDictDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s starDictDo) RightJoin(table schema.Tabler, on ...field.Expr) IStarDictDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s starDictDo) Group(cols ...field.Expr) IStarDictDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s starDictDo) Having(conds ...gen.Condition) IStarDictDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s starDictDo) Limit(limit int) IStarDictDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s starDictDo) Offset(offset int) IStarDictDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s starDictDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IStarDictDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s starDictDo) Unscoped() IStarDictDo {
	return s.withDO(s.DO.Unscoped())
}

func (s starDictDo) Create(values ...*bean.StarDict) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s starDictDo) CreateInBatches(values []*bean.StarDict, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s starDictDo) Save(values ...*bean.StarDict) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s starDictDo) First() (*bean.StarDict, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*bean.StarDict), nil
	}
}

func (s starDictDo) Take() (*bean.StarDict, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*bean.StarDict), nil
	}
}

func (s starDictDo) Last() (*bean.StarDict, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*bean.StarDict), nil
	}
}

func (s starDictDo) Find() ([]*bean.StarDict, error) {
	result, err := s.DO.Find()
	return result.([]*bean.StarDict), err
}

func (s starDictDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*bean.StarDict, err error) {
	buf := make([]*bean.StarDict, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s starDictDo) FindInBatches(result *[]*bean.StarDict, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s starDictDo) Attrs(attrs ...field.AssignExpr) IStarDictDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s starDictDo) Assign(attrs ...field.AssignExpr) IStarDictDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s starDictDo) Joins(fields ...field.RelationField) IStarDictDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s starDictDo) Preload(fields ...field.RelationField) IStarDictDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s starDictDo) FirstOrInit() (*bean.StarDict, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*bean.StarDict), nil
	}
}

func (s starDictDo) FirstOrCreate() (*bean.StarDict, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*bean.StarDict), nil
	}
}

func (s starDictDo) FindByPage(offset int, limit int) (result []*bean.StarDict, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s starDictDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s starDictDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s starDictDo) Delete(models ...*bean.StarDict) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *starDictDo) withDO(do gen.Dao) *starDictDo {
	s.DO = *do.(*gen.DO)
	return s
}
