// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dto

import (
	"context"
	"english-study/internal/model/bean"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newWordStatus(db *gorm.DB, opts ...gen.DOOption) wordStatus {
	_wordStatus := wordStatus{}

	_wordStatus.wordStatusDo.UseDB(db, opts...)
	_wordStatus.wordStatusDo.UseModel(&bean.WordStatus{})

	tableName := _wordStatus.wordStatusDo.TableName()
	_wordStatus.ALL = field.NewAsterisk(tableName)
	_wordStatus.ID = field.NewUint(tableName, "id")
	_wordStatus.WordID = field.NewUint(tableName, "word_id")
	_wordStatus.WordType = field.NewInt(tableName, "word_type")
	_wordStatus.Status = field.NewInt(tableName, "status")
	_wordStatus.Times = field.NewInt(tableName, "times")
	_wordStatus.Weight = field.NewFloat64(tableName, "weight")
	_wordStatus.StudyTime = field.NewTime(tableName, "study_time")
	_wordStatus.EaseFactor = field.NewFloat64(tableName, "ease_factor")
	_wordStatus.Interval = field.NewInt(tableName, "interval")
	_wordStatus.NextReviewAt = field.NewTime(tableName, "next_review_at")
	_wordStatus.Repetitions = field.NewInt(tableName, "repetitions")
	_wordStatus.UserID = field.NewUint(tableName, "user_id")
	_wordStatus.SourceUserID = field.NewUint(tableName, "source_user_id")
	_wordStatus.CreatedAt = field.NewTime(tableName, "created_at")
	_wordStatus.UpdatedAt = field.NewTime(tableName, "updated_at")

	_wordStatus.fillFieldMap()

	return _wordStatus
}

type wordStatus struct {
	wordStatusDo

	ALL          field.Asterisk
	ID           field.Uint
	WordID       field.Uint
	WordType     field.Int
	Status       field.Int
	Times        field.Int
	Weight       field.Float64
	StudyTime    field.Time
	EaseFactor   field.Float64
	Interval     field.Int
	NextReviewAt field.Time
	Repetitions  field.Int
	UserID       field.Uint
	SourceUserID field.Uint
	CreatedAt    field.Time
	UpdatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (w wordStatus) Table(newTableName string) *wordStatus {
	w.wordStatusDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w wordStatus) As(alias string) *wordStatus {
	w.wordStatusDo.DO = *(w.wordStatusDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *wordStatus) updateTableName(table string) *wordStatus {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewUint(table, "id")
	w.WordID = field.NewUint(table, "word_id")
	w.WordType = field.NewInt(table, "word_type")
	w.Status = field.NewInt(table, "status")
	w.Times = field.NewInt(table, "times")
	w.Weight = field.NewFloat64(table, "weight")
	w.StudyTime = field.NewTime(table, "study_time")
	w.EaseFactor = field.NewFloat64(table, "ease_factor")
	w.Interval = field.NewInt(table, "interval")
	w.NextReviewAt = field.NewTime(table, "next_review_at")
	w.Repetitions = field.NewInt(table, "repetitions")
	w.UserID = field.NewUint(table, "user_id")
	w.SourceUserID = field.NewUint(table, "source_user_id")
	w.CreatedAt = field.NewTime(table, "created_at")
	w.UpdatedAt = field.NewTime(table, "updated_at")

	w.fillFieldMap()

	return w
}

func (w *wordStatus) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *wordStatus) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 15)
	w.fieldMap["id"] = w.ID
	w.fieldMap["word_id"] = w.WordID
	w.fieldMap["word_type"] = w.WordType
	w.fieldMap["status"] = w.Status
	w.fieldMap["times"] = w.Times
	w.fieldMap["weight"] = w.Weight
	w.fieldMap["study_time"] = w.StudyTime
	w.fieldMap["ease_factor"] = w.EaseFactor
	w.fieldMap["interval"] = w.Interval
	w.fieldMap["next_review_at"] = w.NextReviewAt
	w.fieldMap["repetitions"] = w.Repetitions
	w.fieldMap["user_id"] = w.UserID
	w.fieldMap["source_user_id"] = w.SourceUserID
	w.fieldMap["created_at"] = w.CreatedAt
	w.fieldMap["updated_at"] = w.UpdatedAt
}

func (w wordStatus) clone(db *gorm.DB) wordStatus {
	w.wordStatusDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w wordStatus) replaceDB(db *gorm.DB) wordStatus {
	w.wordStatusDo.ReplaceDB(db)
	return w
}

type wordStatusDo struct{ gen.DO }

type IWordStatusDo interface {
	gen.SubQuery
	Debug() IWordStatusDo
	WithContext(ctx context.Context) IWordStatusDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWordStatusDo
	WriteDB() IWordStatusDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWordStatusDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWordStatusDo
	Not(conds ...gen.Condition) IWordStatusDo
	Or(conds ...gen.Condition) IWordStatusDo
	Select(conds ...field.Expr) IWordStatusDo
	Where(conds ...gen.Condition) IWordStatusDo
	Order(conds ...field.Expr) IWordStatusDo
	Distinct(cols ...field.Expr) IWordStatusDo
	Omit(cols ...field.Expr) IWordStatusDo
	Join(table schema.Tabler, on ...field.Expr) IWordStatusDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWordStatusDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWordStatusDo
	Group(cols ...field.Expr) IWordStatusDo
	Having(conds ...gen.Condition) IWordStatusDo
	Limit(limit int) IWordStatusDo
	Offset(offset int) IWordStatusDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWordStatusDo
	Unscoped() IWordStatusDo
	Create(values ...*bean.WordStatus) error
	CreateInBatches(values []*bean.WordStatus, batchSize int) error
	Save(values ...*bean.WordStatus) error
	First() (*bean.WordStatus, error)
	Take() (*bean.WordStatus, error)
	Last() (*bean.WordStatus, error)
	Find() ([]*bean.WordStatus, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*bean.WordStatus, err error)
	FindInBatches(result *[]*bean.WordStatus, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*bean.WordStatus) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWordStatusDo
	Assign(attrs ...field.AssignExpr) IWordStatusDo
	Joins(fields ...field.RelationField) IWordStatusDo
	Preload(fields ...field.RelationField) IWordStatusDo
	FirstOrInit() (*bean.WordStatus, error)
	FirstOrCreate() (*bean.WordStatus, error)
	FindByPage(offset int, limit int) (result []*bean.WordStatus, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWordStatusDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w wordStatusDo) Debug() IWordStatusDo {
	return w.withDO(w.DO.Debug())
}

func (w wordStatusDo) WithContext(ctx context.Context) IWordStatusDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w wordStatusDo) ReadDB() IWordStatusDo {
	return w.Clauses(dbresolver.Read)
}

func (w wordStatusDo) WriteDB() IWordStatusDo {
	return w.Clauses(dbresolver.Write)
}

func (w wordStatusDo) Session(config *gorm.Session) IWordStatusDo {
	return w.withDO(w.DO.Session(config))
}

func (w wordStatusDo) Clauses(conds ...clause.Expression) IWordStatusDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w wordStatusDo) Returning(value interface{}, columns ...string) IWordStatusDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w wordStatusDo) Not(conds ...gen.Condition) IWordStatusDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w wordStatusDo) Or(conds ...gen.Condition) IWordStatusDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w wordStatusDo) Select(conds ...field.Expr) IWordStatusDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w wordStatusDo) Where(conds ...gen.Condition) IWordStatusDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w wordStatusDo) Order(conds ...field.Expr) IWordStatusDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w wordStatusDo) Distinct(cols ...field.Expr) IWordStatusDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w wordStatusDo) Omit(cols ...field.Expr) IWordStatusDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w wordStatusDo) Join(table schema.Tabler, on ...field.Expr) IWordStatusDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w wordStatusDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWordStatusDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w wordStatusDo) RightJoin(table schema.Tabler, on ...field.Expr) IWordStatusDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w wordStatusDo) Group(cols ...field.Expr) IWordStatusDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w wordStatusDo) Having(conds ...gen.Condition) IWordStatusDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w wordStatusDo) Limit(limit int) IWordStatusDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w wordStatusDo) Offset(offset int) IWordStatusDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w wordStatusDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWordStatusDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w wordStatusDo) Unscoped() IWordStatusDo {
	return w.withDO(w.DO.Unscoped())
}

func (w wordStatusDo) Create(values ...*bean.WordStatus) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w wordStatusDo) CreateInBatches(values []*bean.WordStatus, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w wordStatusDo) Save(values ...*bean.WordStatus) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w wordStatusDo) First() (*bean.WordStatus, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*bean.WordStatus), nil
	}
}

func (w wordStatusDo) Take() (*bean.WordStatus, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*bean.WordStatus), nil
	}
}

func (w wordStatusDo) Last() (*bean.WordStatus, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*bean.WordStatus), nil
	}
}

func (w wordStatusDo) Find() ([]*bean.WordStatus, error) {
	result, err := w.DO.Find()
	return result.([]*bean.WordStatus), err
}

func (w wordStatusDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*bean.WordStatus, err error) {
	buf := make([]*bean.WordStatus, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w wordStatusDo) FindInBatches(result *[]*bean.WordStatus, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w wordStatusDo) Attrs(attrs ...field.AssignExpr) IWordStatusDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w wordStatusDo) Assign(attrs ...field.AssignExpr) IWordStatusDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w wordStatusDo) Joins(fields ...field.RelationField) IWordStatusDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w wordStatusDo) Preload(fields ...field.RelationField) IWordStatusDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w wordStatusDo) FirstOrInit() (*bean.WordStatus, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*bean.WordStatus), nil
	}
}

func (w wordStatusDo) FirstOrCreate() (*bean.WordStatus, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*bean.WordStatus), nil
	}
}

func (w wordStatusDo) FindByPage(offset int, limit int) (result []*bean.WordStatus, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w wordStatusDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w wordStatusDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w wordStatusDo) Delete(models ...*bean.WordStatus) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *wordStatusDo) withDO(do gen.Dao) *wordStatusDo {
	w.DO = *do.(*gen.DO)
	return w
}
