// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dto

import (
	"context"
	"english-study/internal/model/bean"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newWordPos(db *gorm.DB, opts ...gen.DOOption) wordPos {
	_wordPos := wordPos{}

	_wordPos.wordPosDo.UseDB(db, opts...)
	_wordPos.wordPosDo.UseModel(&bean.WordPos{})

	tableName := _wordPos.wordPosDo.TableName()
	_wordPos.ALL = field.NewAsterisk(tableName)
	_wordPos.ID = field.NewUint(tableName, "id")
	_wordPos.WordID = field.NewUint(tableName, "word_id")
	_wordPos.Word = field.NewString(tableName, "word")
	_wordPos.Pos = field.NewInt(tableName, "pos")
	_wordPos.Translation = field.NewString(tableName, "translation")
	_wordPos.Example = field.NewString(tableName, "example")
	_wordPos.Picture = field.NewString(tableName, "picture")
	_wordPos.Exchange = field.NewString(tableName, "exchange")
	_wordPos.UpdatedAt = field.NewTime(tableName, "updated_at")

	_wordPos.fillFieldMap()

	return _wordPos
}

type wordPos struct {
	wordPosDo

	ALL         field.Asterisk
	ID          field.Uint
	WordID      field.Uint
	Word        field.String
	Pos         field.Int
	Translation field.String
	Example     field.String
	Picture     field.String
	Exchange    field.String
	UpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (w wordPos) Table(newTableName string) *wordPos {
	w.wordPosDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w wordPos) As(alias string) *wordPos {
	w.wordPosDo.DO = *(w.wordPosDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *wordPos) updateTableName(table string) *wordPos {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewUint(table, "id")
	w.WordID = field.NewUint(table, "word_id")
	w.Word = field.NewString(table, "word")
	w.Pos = field.NewInt(table, "pos")
	w.Translation = field.NewString(table, "translation")
	w.Example = field.NewString(table, "example")
	w.Picture = field.NewString(table, "picture")
	w.Exchange = field.NewString(table, "exchange")
	w.UpdatedAt = field.NewTime(table, "updated_at")

	w.fillFieldMap()

	return w
}

func (w *wordPos) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *wordPos) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 9)
	w.fieldMap["id"] = w.ID
	w.fieldMap["word_id"] = w.WordID
	w.fieldMap["word"] = w.Word
	w.fieldMap["pos"] = w.Pos
	w.fieldMap["translation"] = w.Translation
	w.fieldMap["example"] = w.Example
	w.fieldMap["picture"] = w.Picture
	w.fieldMap["exchange"] = w.Exchange
	w.fieldMap["updated_at"] = w.UpdatedAt
}

func (w wordPos) clone(db *gorm.DB) wordPos {
	w.wordPosDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w wordPos) replaceDB(db *gorm.DB) wordPos {
	w.wordPosDo.ReplaceDB(db)
	return w
}

type wordPosDo struct{ gen.DO }

type IWordPosDo interface {
	gen.SubQuery
	Debug() IWordPosDo
	WithContext(ctx context.Context) IWordPosDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWordPosDo
	WriteDB() IWordPosDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWordPosDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWordPosDo
	Not(conds ...gen.Condition) IWordPosDo
	Or(conds ...gen.Condition) IWordPosDo
	Select(conds ...field.Expr) IWordPosDo
	Where(conds ...gen.Condition) IWordPosDo
	Order(conds ...field.Expr) IWordPosDo
	Distinct(cols ...field.Expr) IWordPosDo
	Omit(cols ...field.Expr) IWordPosDo
	Join(table schema.Tabler, on ...field.Expr) IWordPosDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWordPosDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWordPosDo
	Group(cols ...field.Expr) IWordPosDo
	Having(conds ...gen.Condition) IWordPosDo
	Limit(limit int) IWordPosDo
	Offset(offset int) IWordPosDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWordPosDo
	Unscoped() IWordPosDo
	Create(values ...*bean.WordPos) error
	CreateInBatches(values []*bean.WordPos, batchSize int) error
	Save(values ...*bean.WordPos) error
	First() (*bean.WordPos, error)
	Take() (*bean.WordPos, error)
	Last() (*bean.WordPos, error)
	Find() ([]*bean.WordPos, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*bean.WordPos, err error)
	FindInBatches(result *[]*bean.WordPos, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*bean.WordPos) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWordPosDo
	Assign(attrs ...field.AssignExpr) IWordPosDo
	Joins(fields ...field.RelationField) IWordPosDo
	Preload(fields ...field.RelationField) IWordPosDo
	FirstOrInit() (*bean.WordPos, error)
	FirstOrCreate() (*bean.WordPos, error)
	FindByPage(offset int, limit int) (result []*bean.WordPos, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWordPosDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w wordPosDo) Debug() IWordPosDo {
	return w.withDO(w.DO.Debug())
}

func (w wordPosDo) WithContext(ctx context.Context) IWordPosDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w wordPosDo) ReadDB() IWordPosDo {
	return w.Clauses(dbresolver.Read)
}

func (w wordPosDo) WriteDB() IWordPosDo {
	return w.Clauses(dbresolver.Write)
}

func (w wordPosDo) Session(config *gorm.Session) IWordPosDo {
	return w.withDO(w.DO.Session(config))
}

func (w wordPosDo) Clauses(conds ...clause.Expression) IWordPosDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w wordPosDo) Returning(value interface{}, columns ...string) IWordPosDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w wordPosDo) Not(conds ...gen.Condition) IWordPosDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w wordPosDo) Or(conds ...gen.Condition) IWordPosDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w wordPosDo) Select(conds ...field.Expr) IWordPosDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w wordPosDo) Where(conds ...gen.Condition) IWordPosDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w wordPosDo) Order(conds ...field.Expr) IWordPosDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w wordPosDo) Distinct(cols ...field.Expr) IWordPosDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w wordPosDo) Omit(cols ...field.Expr) IWordPosDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w wordPosDo) Join(table schema.Tabler, on ...field.Expr) IWordPosDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w wordPosDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWordPosDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w wordPosDo) RightJoin(table schema.Tabler, on ...field.Expr) IWordPosDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w wordPosDo) Group(cols ...field.Expr) IWordPosDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w wordPosDo) Having(conds ...gen.Condition) IWordPosDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w wordPosDo) Limit(limit int) IWordPosDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w wordPosDo) Offset(offset int) IWordPosDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w wordPosDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWordPosDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w wordPosDo) Unscoped() IWordPosDo {
	return w.withDO(w.DO.Unscoped())
}

func (w wordPosDo) Create(values ...*bean.WordPos) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w wordPosDo) CreateInBatches(values []*bean.WordPos, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w wordPosDo) Save(values ...*bean.WordPos) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w wordPosDo) First() (*bean.WordPos, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*bean.WordPos), nil
	}
}

func (w wordPosDo) Take() (*bean.WordPos, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*bean.WordPos), nil
	}
}

func (w wordPosDo) Last() (*bean.WordPos, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*bean.WordPos), nil
	}
}

func (w wordPosDo) Find() ([]*bean.WordPos, error) {
	result, err := w.DO.Find()
	return result.([]*bean.WordPos), err
}

func (w wordPosDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*bean.WordPos, err error) {
	buf := make([]*bean.WordPos, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w wordPosDo) FindInBatches(result *[]*bean.WordPos, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w wordPosDo) Attrs(attrs ...field.AssignExpr) IWordPosDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w wordPosDo) Assign(attrs ...field.AssignExpr) IWordPosDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w wordPosDo) Joins(fields ...field.RelationField) IWordPosDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w wordPosDo) Preload(fields ...field.RelationField) IWordPosDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w wordPosDo) FirstOrInit() (*bean.WordPos, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*bean.WordPos), nil
	}
}

func (w wordPosDo) FirstOrCreate() (*bean.WordPos, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*bean.WordPos), nil
	}
}

func (w wordPosDo) FindByPage(offset int, limit int) (result []*bean.WordPos, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w wordPosDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w wordPosDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w wordPosDo) Delete(models ...*bean.WordPos) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *wordPosDo) withDO(do gen.Dao) *wordPosDo {
	w.DO = *do.(*gen.DO)
	return w
}
