// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dto

import (
	"context"
	"english-study/internal/model/bean"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newWordPhrase(db *gorm.DB, opts ...gen.DOOption) wordPhrase {
	_wordPhrase := wordPhrase{}

	_wordPhrase.wordPhraseDo.UseDB(db, opts...)
	_wordPhrase.wordPhraseDo.UseModel(&bean.WordPhrase{})

	tableName := _wordPhrase.wordPhraseDo.TableName()
	_wordPhrase.ALL = field.NewAsterisk(tableName)
	_wordPhrase.ID = field.NewUint(tableName, "id")
	_wordPhrase.Phrase = field.NewString(tableName, "phrase")
	_wordPhrase.Translation = field.NewString(tableName, "translation")
	_wordPhrase.Pronunciation = field.NewString(tableName, "pronunciation")
	_wordPhrase.Example = field.NewString(tableName, "example")
	_wordPhrase.Picture = field.NewString(tableName, "picture")

	_wordPhrase.fillFieldMap()

	return _wordPhrase
}

type wordPhrase struct {
	wordPhraseDo

	ALL           field.Asterisk
	ID            field.Uint
	Phrase        field.String
	Translation   field.String
	Pronunciation field.String
	Example       field.String
	Picture       field.String

	fieldMap map[string]field.Expr
}

func (w wordPhrase) Table(newTableName string) *wordPhrase {
	w.wordPhraseDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w wordPhrase) As(alias string) *wordPhrase {
	w.wordPhraseDo.DO = *(w.wordPhraseDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *wordPhrase) updateTableName(table string) *wordPhrase {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewUint(table, "id")
	w.Phrase = field.NewString(table, "phrase")
	w.Translation = field.NewString(table, "translation")
	w.Pronunciation = field.NewString(table, "pronunciation")
	w.Example = field.NewString(table, "example")
	w.Picture = field.NewString(table, "picture")

	w.fillFieldMap()

	return w
}

func (w *wordPhrase) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *wordPhrase) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 6)
	w.fieldMap["id"] = w.ID
	w.fieldMap["phrase"] = w.Phrase
	w.fieldMap["translation"] = w.Translation
	w.fieldMap["pronunciation"] = w.Pronunciation
	w.fieldMap["example"] = w.Example
	w.fieldMap["picture"] = w.Picture
}

func (w wordPhrase) clone(db *gorm.DB) wordPhrase {
	w.wordPhraseDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w wordPhrase) replaceDB(db *gorm.DB) wordPhrase {
	w.wordPhraseDo.ReplaceDB(db)
	return w
}

type wordPhraseDo struct{ gen.DO }

type IWordPhraseDo interface {
	gen.SubQuery
	Debug() IWordPhraseDo
	WithContext(ctx context.Context) IWordPhraseDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWordPhraseDo
	WriteDB() IWordPhraseDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWordPhraseDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWordPhraseDo
	Not(conds ...gen.Condition) IWordPhraseDo
	Or(conds ...gen.Condition) IWordPhraseDo
	Select(conds ...field.Expr) IWordPhraseDo
	Where(conds ...gen.Condition) IWordPhraseDo
	Order(conds ...field.Expr) IWordPhraseDo
	Distinct(cols ...field.Expr) IWordPhraseDo
	Omit(cols ...field.Expr) IWordPhraseDo
	Join(table schema.Tabler, on ...field.Expr) IWordPhraseDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWordPhraseDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWordPhraseDo
	Group(cols ...field.Expr) IWordPhraseDo
	Having(conds ...gen.Condition) IWordPhraseDo
	Limit(limit int) IWordPhraseDo
	Offset(offset int) IWordPhraseDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWordPhraseDo
	Unscoped() IWordPhraseDo
	Create(values ...*bean.WordPhrase) error
	CreateInBatches(values []*bean.WordPhrase, batchSize int) error
	Save(values ...*bean.WordPhrase) error
	First() (*bean.WordPhrase, error)
	Take() (*bean.WordPhrase, error)
	Last() (*bean.WordPhrase, error)
	Find() ([]*bean.WordPhrase, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*bean.WordPhrase, err error)
	FindInBatches(result *[]*bean.WordPhrase, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*bean.WordPhrase) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWordPhraseDo
	Assign(attrs ...field.AssignExpr) IWordPhraseDo
	Joins(fields ...field.RelationField) IWordPhraseDo
	Preload(fields ...field.RelationField) IWordPhraseDo
	FirstOrInit() (*bean.WordPhrase, error)
	FirstOrCreate() (*bean.WordPhrase, error)
	FindByPage(offset int, limit int) (result []*bean.WordPhrase, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWordPhraseDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w wordPhraseDo) Debug() IWordPhraseDo {
	return w.withDO(w.DO.Debug())
}

func (w wordPhraseDo) WithContext(ctx context.Context) IWordPhraseDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w wordPhraseDo) ReadDB() IWordPhraseDo {
	return w.Clauses(dbresolver.Read)
}

func (w wordPhraseDo) WriteDB() IWordPhraseDo {
	return w.Clauses(dbresolver.Write)
}

func (w wordPhraseDo) Session(config *gorm.Session) IWordPhraseDo {
	return w.withDO(w.DO.Session(config))
}

func (w wordPhraseDo) Clauses(conds ...clause.Expression) IWordPhraseDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w wordPhraseDo) Returning(value interface{}, columns ...string) IWordPhraseDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w wordPhraseDo) Not(conds ...gen.Condition) IWordPhraseDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w wordPhraseDo) Or(conds ...gen.Condition) IWordPhraseDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w wordPhraseDo) Select(conds ...field.Expr) IWordPhraseDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w wordPhraseDo) Where(conds ...gen.Condition) IWordPhraseDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w wordPhraseDo) Order(conds ...field.Expr) IWordPhraseDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w wordPhraseDo) Distinct(cols ...field.Expr) IWordPhraseDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w wordPhraseDo) Omit(cols ...field.Expr) IWordPhraseDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w wordPhraseDo) Join(table schema.Tabler, on ...field.Expr) IWordPhraseDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w wordPhraseDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWordPhraseDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w wordPhraseDo) RightJoin(table schema.Tabler, on ...field.Expr) IWordPhraseDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w wordPhraseDo) Group(cols ...field.Expr) IWordPhraseDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w wordPhraseDo) Having(conds ...gen.Condition) IWordPhraseDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w wordPhraseDo) Limit(limit int) IWordPhraseDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w wordPhraseDo) Offset(offset int) IWordPhraseDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w wordPhraseDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWordPhraseDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w wordPhraseDo) Unscoped() IWordPhraseDo {
	return w.withDO(w.DO.Unscoped())
}

func (w wordPhraseDo) Create(values ...*bean.WordPhrase) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w wordPhraseDo) CreateInBatches(values []*bean.WordPhrase, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w wordPhraseDo) Save(values ...*bean.WordPhrase) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w wordPhraseDo) First() (*bean.WordPhrase, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*bean.WordPhrase), nil
	}
}

func (w wordPhraseDo) Take() (*bean.WordPhrase, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*bean.WordPhrase), nil
	}
}

func (w wordPhraseDo) Last() (*bean.WordPhrase, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*bean.WordPhrase), nil
	}
}

func (w wordPhraseDo) Find() ([]*bean.WordPhrase, error) {
	result, err := w.DO.Find()
	return result.([]*bean.WordPhrase), err
}

func (w wordPhraseDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*bean.WordPhrase, err error) {
	buf := make([]*bean.WordPhrase, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w wordPhraseDo) FindInBatches(result *[]*bean.WordPhrase, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w wordPhraseDo) Attrs(attrs ...field.AssignExpr) IWordPhraseDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w wordPhraseDo) Assign(attrs ...field.AssignExpr) IWordPhraseDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w wordPhraseDo) Joins(fields ...field.RelationField) IWordPhraseDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w wordPhraseDo) Preload(fields ...field.RelationField) IWordPhraseDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w wordPhraseDo) FirstOrInit() (*bean.WordPhrase, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*bean.WordPhrase), nil
	}
}

func (w wordPhraseDo) FirstOrCreate() (*bean.WordPhrase, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*bean.WordPhrase), nil
	}
}

func (w wordPhraseDo) FindByPage(offset int, limit int) (result []*bean.WordPhrase, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w wordPhraseDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w wordPhraseDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w wordPhraseDo) Delete(models ...*bean.WordPhrase) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *wordPhraseDo) withDO(do gen.Dao) *wordPhraseDo {
	w.DO = *do.(*gen.DO)
	return w
}
