// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type AddTagReq struct {
	Name     string `json:"name"`
	Style    string `json:"style"`
	IsSystem bool   `json:"is_system,optional"` // true=系统标签, 仅超管可设
}

type AddTagResp struct {
	CommonReply
}

type AddWordPhraseReq struct {
	Phrase            string     `json:"phrase"`                       // 短语
	Translation       string     `json:"translation,optional"`         // 中文翻译
	Pronunciation     string     `json:"pronunciation,optional"`       // 发音
	Example           []*Example `json:"example,optional"`             // 例句
	Picture           string     `json:"picture,optional"`             // 图片
	IsGeneratePicture bool       `json:"is_generate_picture,optional"` // 是否生成图片
}

type AddWordPhraseResp struct {
	CommonReply
}

type AddWordReq struct {
	Word              string     `json:"word"`                         // 单词
	UKPhonetic        string     `json:"uk_phonetic,optional"`         // 英式音标
	UKAudio           string     `json:"uk_audio,optional"`            // 英式音频
	USPhonetic        string     `json:"us_phonetic,optional"`         // 美式音标
	USAudio           string     `json:"us_audio,optional"`            // 美式音频
	Pos               []*WordPos `json:"pos,optional"`                 // 词性
	IsGeneratePicture bool       `json:"is_generate_picture,optional"` // 是否生成图片
}

type AddWordResp struct {
	CommonReply
}

type ArticleCandidate struct {
	WordID   uint   `json:"word_id"`
	WordType int    `json:"word_type"`
	Word     string `json:"word"`
	PosLabel string `json:"pos_label"`
	Meaning  string `json:"meaning"`
	Phonetic string `json:"phonetic"`
}

type ArticleCandidatesReq struct {
	Status   int    `form:"status,optional"`   // 0-全部 1-4
	Category int    `form:"category,optional"` // 1-标签 2-单词 3-词语 4-全部
	TagIDs   []uint `form:"tag_ids,optional"`
}

type ArticleCandidatesResp struct {
	CommonReply
	Data []*ArticleCandidate `json:"data"`
}

type ArticleDetailReq struct {
	ID uint `form:"id"`
}

type ArticleDetailResp struct {
	CommonReply
	Data ArticleView `json:"data"`
}

type ArticleListItem struct {
	ID        uint         `json:"id"`
	TitleEn   string       `json:"title_en"`
	TitleZh   string       `json:"title_zh"`
	Tags      []ArticleTag `json:"tags"`
	Words     []string     `json:"words"` // 含词原文(小字展示)
	CreatedAt string       `json:"created_at"`
}

type ArticleSense struct {
	PosLabel string `json:"pos_label"` // 词性缩写, 如 n. / vt. / vi.
	Meaning  string `json:"meaning"`   // 该词性下的中文释义
}

type ArticleSentence struct {
	En string `json:"en"` // 英文
	Zh string `json:"zh"` // 中文
}

type ArticleTag struct {
	TagID uint   `json:"tag_id"`
	Name  string `json:"name"`
	Style string `json:"style"`
}

type ArticleUsedWord struct {
	WordID   uint           `json:"word_id"`   // 词条ID(收录时建 article_words 用)
	WordType int            `json:"word_type"` // 1-单词 2-短语
	Word     string         `json:"word"`      // 原型
	Surfaces []string       `json:"surfaces"`  // 正文中出现的字面形式(含变形)
	PosLabel string         `json:"pos_label"` // 主词性缩写(兼容; 气泡卡优先用 senses)
	Meaning  string         `json:"meaning"`   // 合并释义(兼容)
	Senses   []ArticleSense `json:"senses"`    // 全部词性+释义, 气泡卡按词性分行
	Phonetic string         `json:"phonetic"`  // 音标(后端补齐)
	Found    bool           `json:"found"`     // 词条当前是否仍存在于词库
}

type ArticleView struct {
	ID        uint              `json:"id"` // 未收录时为 0
	TitleEn   string            `json:"title_en"`
	TitleZh   string            `json:"title_zh"`
	Tags      []ArticleTag      `json:"tags"` // 计算得到
	Sentences []ArticleSentence `json:"sentences"`
	UsedWords []ArticleUsedWord `json:"used_words"`
	CreatedAt string            `json:"created_at,optional"`
}

type BatchAddStardictItem struct {
	Sw       string `json:"sw"`
	WordType int    `json:"word_type"`
}

type BatchAddStardictReq struct {
	Items []BatchAddStardictItem `json:"items"`
}

type BatchAddStardictResp struct {
	CommonReply
	Submitted int `json:"submitted"`
}

type CommonReply struct {
	Code   int32  `json:"code"`            // 状态码
	Msg    string `json:"message"`         // 错误信息
	Reason string `json:"reason,optional"` // 错误原因
}

type DashboardData struct {
	StudyCount        int     `json:"study_count"`        // 待学习数量 (status=1)
	ReviewCount       int     `json:"review_count"`       // 今日待复习 (status=2 且 next_review_at<=now)
	StrengthenCount   int     `json:"strengthen_count"`   // 今日待加强 (status=3 且 next_review_at<=now)
	SpotCount         int     `json:"spot_count"`         // 可抽查数量 (status=4)
	TodayStudied      int     `json:"today_studied"`      // 今日已学习
	TodayReviewed     int     `json:"today_reviewed"`     // 今日已复习
	TodayStrengthened int     `json:"today_strengthened"` // 今日已加强
	TotalWords        int     `json:"total_words"`        // 总词条数
	FinishedWords     int     `json:"finished_words"`     // 已掌握数
	ProgressRate      float64 `json:"progress_rate"`      // 掌握进度 0-1
}

type DeletePhrasePictureReq struct {
	ID uint `json:"id"` // 短语ID
}

type DeletePhrasePictureResp struct {
	CommonReply
}

type DeleteTagReq struct {
	ID uint `json:"id"` // 标签ID
}

type DeleteTagResp struct {
	CommonReply
}

type DeleteWordPhraseReq struct {
	ID uint `json:"id"` // 短语ID
}

type DeleteWordPhraseResp struct {
	CommonReply
}

type DeleteWordPictureReq struct {
	WordPosId uint `json:"word_pos_id"` // 单词词性ID
}

type DeleteWordPictureResp struct {
	CommonReply
}

type DeleteWordReq struct {
	ID uint `json:"id"` // 单词ID
}

type DeleteWordResp struct {
	CommonReply
}

type Example struct {
	Example     string `json:"example"`     // 例句
	Translation string `json:"translation"` // 中文翻译
}

type ExportWordReq struct {
}

type ExportWordResp struct {
	CommonReply
	FilePath string `json:"file_path"` // 文件路径
}

type FileDownloadReq struct {
	Path string `form:"path"` // 文件路径, 例如: englishstudy/xx/xx.jpg
}

type FileDownloadResp struct {
	CommonReply
	Url string `json:"url"` // 文件url, 例如: https://englishstudy.oss-cn-beijing.aliyuncs.com/xx/xx.jpg
}

type FileUploadReq struct {
	Bucket string `form:"bucket"` // 桶名, 例如: englishstudy
	Object string `form:"object"` // 对象名, xx/xx.jpg
}

type FileUploadResp struct {
	CommonReply
	Path string `json:"path"` // 文件路径, 由桶名和对象名组成, 例如: englishstudy/xx/xx.jpg
}

type FinishReviewReq struct {
	WordID    uint `json:"word_id"`                    // 单词ID
	WordType  int  `json:"word_type"`                  // 单词类型 1-单词 2-短语
	Operation int  `json:"operation"`                  // 操作 1-完成复习 2-复习失败
	Quality   int  `json:"quality,optional,default=4"` // SM-2质量评分 3-5
}

type FinishReviewResp struct {
	CommonReply
}

type FinishSpotReq struct {
	WordID    uint `json:"word_id"`   // 单词ID
	WordType  int  `json:"word_type"` // 单词类型 1-单词 2-短语
	Operation int  `json:"operation"` // 操作 1-完成抽查 2-抽查失败
}

type FinishSpotResp struct {
	CommonReply
}

type FinishStrengthReq struct {
	WordID    uint `json:"word_id"`   // 单词ID
	WordType  int  `json:"word_type"` // 单词类型 1-单词 2-短语
	Operation int  `json:"operation"` // 操作 1-完成强化 2-强化失败
}

type FinishStrengthResp struct {
	CommonReply
}

type FinishStudyReq struct {
	WordID   uint `json:"word_id"`   // 单词ID
	WordType int  `json:"word_type"` // 单词类型 1-单词 2-短语
}

type FinishStudyResp struct {
	CommonReply
}

type GenerateArticleReq struct {
	Method   int              `json:"method"`            // 1-随机 2-自选
	Count    int              `json:"count,optional"`    // 随机词数 3~8
	Status   int              `json:"status,optional"`   // 词状态 0-全部 1-学习 2-复习 3-强化 4-完成
	Category int              `json:"category,optional"` // 类别 1-标签 2-单词 3-词语 4-全部
	TagIDs   []uint           `json:"tag_ids,optional"`  // category=1 时生效
	Words    []SelfSelectWord `json:"words,optional"`    // method=2 自选时的词条
}

type GenerateArticleResp struct {
	CommonReply
	Data ArticleView `json:"data"` // ID=0, 未持久化
}

type GenerateExampleReq struct {
	WordPosId   uint   `json:"word_pos_id"` // 单词词性ID
	Translation string `json:"translation"` // 指定某中文翻译
}

type GenerateExampleResp struct {
	CommonReply
	Example Example `json:"example"` // 例句
}

type GeneratePhraseExampleReq struct {
	ID          uint   `json:"id"`                   // 短语ID
	Translation string `json:"translation,optional"` // 指定某中文翻译
}

type GeneratePhraseExampleResp struct {
	CommonReply
	Example Example `json:"example"` // 例句
}

type GeneratePhrasePictureReq struct {
	ID uint `json:"id"` // 短语ID
}

type GeneratePhrasePictureResp struct {
	CommonReply
	Link string `json:"link"` // 图片链接
}

type GenerateShareReq struct {
	ShareType int    `json:"share_type"`       // 0-全部 1-按标签
	WordType  int    `json:"word_type"`        // 0-全部 1-单词 2-短语
	TagIDs    []uint `json:"tag_ids,optional"` // share_type=1 时使用
}

type GenerateShareResp struct {
	CommonReply
	Token     string `json:"token"`      // 分享码
	ExpiresAt int64  `json:"expires_at"` // 过期时间(unix秒)
}

type GenerateWordPictureReq struct {
	WordPosId uint `json:"word_pos_id"` // 单词词性ID
}

type GenerateWordPictureResp struct {
	CommonReply
	Link string `json:"link"` // 图片链接
}

type GetDashboardResp struct {
	CommonReply
	Data DashboardData `json:"data"`
}

type GetDictionaryCountResp struct {
	CommonReply
	WordCount   int `json:"word_count"`   // 单词总数
	PhraseCount int `json:"phrase_count"` // 短语总数
	TotalCount  int `json:"total_count"`  // 总词汇量
}

type GetImportTaskListReq struct {
	StartDate string `form:"start_date,optional"` // 起始日期 YYYY-MM-DD
	EndDate   string `form:"end_date,optional"`   // 结束日期 YYYY-MM-DD
	Days      int    `form:"days,optional"`       // 最近N天（与日期范围互斥，0表示不用）
}

type GetImportTaskListResp struct {
	CommonReply
	Tasks []ImportTaskItem `json:"tasks"`
}

type GetShareWordDetailReq struct {
	Token    string `json:"token"`
	WordID   uint   `json:"word_id"`
	WordType int    `json:"word_type"` // 1-单词 2-短语
}

type GetShareWordDetailResp struct {
	CommonReply
	Word   *Word       `json:"word,optional"`
	Phrase *WordPhrase `json:"phrase,optional"`
}

type GetTagDetailReq struct {
	ID uint `form:"id"` // 标签ID
}

type GetTagDetailResp struct {
	CommonReply
	Data Tag `json:"data"`
}

type GetTagListReq struct {
	PageReq
}

type GetTagListResp struct {
	CommonReply
	PageReply
	Data []*Tag `json:"data"`
}

type GetUserInfoReq struct {
	PathIDReq
}

type GetUserInfoResp struct {
	CommonReply
	UserInfo UserInfo `json:"data"` // 用户信息
}

type GetWordCardListReq struct {
	Count    int    `form:"count,default=10"`   // 单词数量
	Random   bool   `form:"random"`             // 是否随机
	WordType int    `form:"word_type,optional"` // 单词类型 0-都行 1-单词 2-短语
	TagIDs   []uint `form:"tag_ids,optional"`   // 全局标签筛选: 只取打了任一标签的词; 空=不筛选
}

type GetWordCardListResp struct {
	CommonReply
	Data []*WordCard `json:"data"`
}

type GetWordDetailReq struct {
	Id uint `form:"id"` // 单词ID
}

type GetWordDetailResp struct {
	CommonReply
	Data Word `json:"data"`
}

type GetWordListReq struct {
	PageReq
	WordPrefix  string `form:"word_prefix,optional"` // 单词前缀
	Pos         int    `form:"pos,optional"`         // 词性
	Translation string `form:"translation,optional"` // 中文翻译
	Phonetic    string `form:"phonetic,optional"`    // 音标
}

type GetWordListResp struct {
	CommonReply
	PageReply
	Data []*SimpleWord `json:"data"`
}

type GetWordPhraseDetailReq struct {
	ID uint `form:"id"` // 短语ID
}

type GetWordPhraseDetailResp struct {
	CommonReply
	Data WordPhrase `json:"data"`
}

type GetWordPhraseListReq struct {
	PageReq
	WordID       []uint `form:"word_id,optional"`       // 单词ID列表
	PhrasePrefix string `form:"phrase_prefix,optional"` // 短语前缀
	Translation  string `form:"translation,optional"`   // 中文翻译
}

type GetWordPhraseListResp struct {
	CommonReply
	PageReply
	Data []*SimpleWord `json:"data"`
}

type GetWordStatusListReq struct {
	PageReq
	WordID   []uint `form:"word_id,optional"`   // 单词ID列表
	WordType int    `form:"word_type,optional"` // 单词类型, 1-单词 2-短语
}

type GetWordStatusListResp struct {
	CommonReply
	PageReply
	Data []*WordStatus `json:"data"`
}

type GetWordTagListReq struct {
	PageReq
	WordID   []uint `form:"word_id,optional"`   // 单词ID列表
	WordType int    `form:"word_type,optional"` // 单词类型, 1-单词 2-短语
}

type GetWordTagListResp struct {
	CommonReply
	PageReply
	Data []*WordTag `json:"data"`
}

type ImageResult struct {
	ThumbUrl string `json:"thumb_url"` // 缩略图url
	Url      string `json:"url"`       // 原图url
	Width    int    `json:"width"`     // 图片宽度
	Height   int    `json:"height"`    // 图片高度
}

type ImportShareReq struct {
	Token         string `json:"token"`
	TagImportMode int    `json:"tag_import_mode,optional"` // 0-不带 1-仅系统 2-全部 (默认 0)
}

type ImportShareResp struct {
	CommonReply
	WordImported   int `json:"word_imported"`   // 实际导入单词数
	PhraseImported int `json:"phrase_imported"` // 实际导入短语数
	WordSkipped    int `json:"word_skipped"`    // 已存在跳过单词数
	PhraseSkipped  int `json:"phrase_skipped"`  // 已存在跳过短语数
	TagImported    int `json:"tag_imported"`    // 新建标签数
}

type ImportTaskItem struct {
	Id           uint   `json:"id"`
	FileName     string `json:"file_name"`
	Status       int    `json:"status"` // 0-待处理 1-进行中 2-已完成 3-失败
	Total        int    `json:"total"`
	Current      int    `json:"current"`
	CurrentWord  string `json:"current_word"`
	SuccessCount int    `json:"success_count"`
	FailCount    int    `json:"fail_count"`
	FailWords    string `json:"fail_words"` // JSON数组
	CreatedAt    string `json:"created_at"`
}

type ImportWordReq struct {
	FilePath string `json:"file_path"`          // 文件路径
	FileName string `json:"file_name,optional"` // 原始文件名
}

type ImportWordResp struct {
	CommonReply
	TaskId uint `json:"task_id"` // 任务ID
}

type ListArticleReq struct {
	PageReq
	Keyword string `form:"keyword,optional"` // 标题(中英)+含词(英文) 共用
	TagIDs  []uint `form:"tag_ids,optional"` // 标签多选
}

type ListArticleResp struct {
	CommonReply
	PageReply
	Data []*ArticleListItem `json:"data"`
}

type ListWordsByTagsReq struct {
	TagIDs   []uint `form:"tag_ids"`   // 标签ID列表; 返回"同时拥有全部这些标签"的词语(AND)
	WordType int    `form:"word_type"` // 1-单词 2-短语
}

type ListWordsByTagsResp struct {
	CommonReply
	Data []*TaggedWord `json:"data"`
}

type PageReply struct {
	Offset     int   `json:"offset,optional"`
	Limit      int   `json:"limit,optional"`
	TotalCount int64 `json:"total_count"`
}

type PageReq struct {
	Offset  int    `form:"offset,default=0"`
	Limit   int    `form:"limit,default=10"`
	OrderBy string `form:"orderby,optional"`
	Sort    string `form:"sort,default=asc"`
}

type PathIDReq struct {
	PathID string `path:"id"` // 路径 ID
}

type PreviewShareReq struct {
	Token string `json:"token"`
}

type PreviewShareResp struct {
	CommonReply
	FromUsername string            `json:"from_username"` // A 的用户名
	WordCount    int               `json:"word_count"`    // 单词总数
	PhraseCount  int               `json:"phrase_count"`  // 短语总数
	Items        []ShareWordItem   `json:"items"`         // 全部条目
	Tags         []SharePreviewTag `json:"tags"`          // 整体涉及的标签
	ExpiresAt    int64             `json:"expires_at"`    // 过期时间
}

type RelayLoginReq struct {
	AccessKey string `json:"access_key"` // 等同于"AI 辅助密钥", 后端跟 CC.AccessKey 比对
}

type RelayLoginResp struct {
	CommonReply
	AccessToken      string `json:"access_token"`       // 短 TTL JWT (aud=forwarder, token_type=access); 前端连 ws 时放 Sec-WebSocket-Protocol: bearer.<token>
	RefreshToken     string `json:"refresh_token"`      // 长 TTL JWT (aud=forwarder, token_type=refresh); 仅可调 /relay-refresh
	AccessExpiresAt  int64  `json:"access_expires_at"`  // unix sec, 前端 < 60s 内剩余应自动 silent refresh
	RefreshExpiresAt int64  `json:"refresh_expires_at"` // unix sec, refresh 过期 → 前端弹回 AccessKey 输入框
	WsURL            string `json:"ws_url"`             // wss://your-domain/forwarder/ws
}

type RelayRefreshReq struct {
	RefreshToken string `json:"refresh_token"`
}

type SaveArticleReq struct {
	TitleEn   string            `json:"title_en"`
	TitleZh   string            `json:"title_zh"`
	Sentences []ArticleSentence `json:"sentences"`
	UsedWords []ArticleUsedWord `json:"used_words"` // 含 word_id/word_type/word/surfaces
}

type SaveArticleResp struct {
	CommonReply
	ID uint `json:"id"`
}

type SearchImagesReq struct {
	Query  string `form:"query"`           // 搜索关键词
	Offset int    `form:"offset,optional"` // 分页偏移, 默认0
	Count  int    `form:"count,optional"`  // 每页数量, 默认20
}

type SearchImagesResp struct {
	CommonReply
	Images []ImageResult `json:"images"` // 图片结果列表
}

type SearchStardictReq struct {
	Keyword string `form:"keyword"`
	Limit   int    `form:"limit,optional,default=20"`
}

type SearchStardictResp struct {
	CommonReply
	Data []StardictItem `json:"data"`
}

type SelfSelectWord struct {
	WordID   uint `json:"word_id"`
	WordType int  `json:"word_type"` // 1-单词 2-短语
}

type SharePreviewTag struct {
	Name  string `json:"name"`
	Style string `json:"style"`
}

type ShareWordItem struct {
	ID          uint     `json:"id"`          // A 用户里的 id
	WordType    int      `json:"word_type"`   // 1-单词 2-短语
	Text        string   `json:"text"`        // 单词或短语
	Translation string   `json:"translation"` // 中文翻译（简版）
	TagNames    []string `json:"tag_names"`   // 该词关联的标签名
}

type SimpleTagInfo struct {
	ID    uint   `json:"id"`    // 标签ID
	Name  string `json:"name"`  // 标签名称
	Style string `json:"style"` // 展示风格
}

type SimpleWord struct {
	ID   uint   `json:"id"`
	Word string `json:"word"` // 单词
}

type StardictItem struct {
	Sw          string `json:"sw"`
	Phonetic    string `json:"phonetic"`
	Translation string `json:"translation"`
	WordType    int    `json:"word_type"` // 1-单词 2-短语
	IsAdded     bool   `json:"is_added"`
}

type Tag struct {
	ID       uint   `json:"id"`
	Name     string `json:"name"`
	Style    string `json:"style"`
	IsSystem bool   `json:"is_system"` // 是否系统标签 (is_system=true, 对所有用户可见)
}

type TaggedWord struct {
	ID   uint             `json:"id"`   // 词条ID
	Word string           `json:"word"` // 单词/短语文本
	Tags []*SimpleTagInfo `json:"tags"` // 该词条的全部标签
}

type TranslationItem struct {
	ID          uint   `json:"id"`          // word_pos.id (单词) 或 phrase.id (短语)
	Pos         int    `json:"pos"`         // 词性枚举
	PosLabel    string `json:"pos_label"`   // 词性缩写 "n." / "vt." / 短语为空
	Translation string `json:"translation"` // 该条释义
}

type UpdateExampleReq struct {
	WordPosId uint       `json:"word_pos_id"` // 单词词性ID
	Examples  []*Example `json:"examples"`    // 例句
}

type UpdateExampleResp struct {
	CommonReply
}

type UpdatePhraseExampleReq struct {
	ID       uint       `json:"id"`       // 短语ID
	Examples []*Example `json:"examples"` // 例句
}

type UpdatePhraseExampleResp struct {
	CommonReply
}

type UpdatePhrasePictureReq struct {
	ID   uint   `json:"id"`   // 短语ID
	Link string `json:"link"` // 图片链接
}

type UpdatePhrasePictureResp struct {
	CommonReply
}

type UpdateTagReq struct {
	ID    uint   `json:"id"`    // 标签ID
	Name  string `json:"name"`  // 标签名称
	Style string `json:"style"` // 标签样式
}

type UpdateTagResp struct {
	CommonReply
}

type UpdateUserInfoReq struct {
	PathIDReq
	UserInfo UserInfo `json:"data"` // 用户信息
}

type UpdateUserInfoResp struct {
	CommonReply
}

type UpdateWordPhraseReq struct {
	ID            uint       `json:"id"`            // 短语ID
	Phrase        string     `json:"phrase"`        // 短语
	Translation   string     `json:"translation"`   // 中文翻译
	Pronunciation string     `json:"pronunciation"` // 发音
	Example       []*Example `json:"example"`       // 例句
	Picture       string     `json:"picture"`       // 图片
}

type UpdateWordPhraseResp struct {
	CommonReply
}

type UpdateWordPictureReq struct {
	WordPosId uint   `json:"word_pos_id"` // 单词词性ID
	Picture   string `json:"picture"`     // 图片链接
}

type UpdateWordPictureResp struct {
	CommonReply
}

type UpdateWordReq struct {
	ID         uint      `json:"id"`          // 单词ID
	Word       string    `json:"word"`        // 单词
	UKPhonetic string    `json:"uk_phonetic"` // 英式音标
	UKAudio    string    `json:"uk_audio"`    // 英式音频
	USPhonetic string    `json:"us_phonetic"` // 美式音标
	USAudio    string    `json:"us_audio"`    // 美式音频
	Pos        []WordPos `json:"pos"`         // 词性
}

type UpdateWordResp struct {
	CommonReply
}

type UpdateWordStatusReq struct {
	WordID   uint `json:"word_id"`   // 单词ID
	WordType int  `json:"word_type"` // 单词类型, 1-单词 2-短语
	Status   int  `json:"status"`    // 状态
}

type UpdateWordStatusResp struct {
	CommonReply
}

type UpdateWordTagReq struct {
	WordID   uint   `json:"word_id"`   // 单词ID
	WordType int    `json:"word_type"` // 单词类型, 1-单词 2-短语
	Tags     []uint `json:"tags"`      // 标签ID列表
}

type UpdateWordTagResp struct {
	CommonReply
}

type UpdateWordTranslationItem struct {
	WordPosID   uint   `json:"word_pos_id"`
	Translation string `json:"translation"`
}

type UpdateWordTranslationReq struct {
	Items []UpdateWordTranslationItem `json:"items"`
}

type UpdateWordTranslationResp struct {
	CommonReply
}

type UserInfo struct {
	ID      uint   `json:"id"`
	Name    string `json:"name"`
	Account string `json:"account"`
	Phone   string `json:"phone"`
	Email   string `json:"email"`
	Avatar  string `json:"avatar"` // 头像
	Role    int    `json:"role"`   // 角色 0-普通 1-超管 (前端 UI 显隐用, 鉴权仍在服务端 JWT)
}

type UserLoginReq struct {
	Account  string `json:"account"`  // 账号
	Password string `json:"password"` // 密码
}

type UserLoginResp struct {
	CommonReply
	Token    string   `json:"token"` // 访问令牌
	UserInfo UserInfo `json:"data"`  // 用户信息
}

type UserLoginWxReq struct {
	Code string `json:"code"` // 微信登录code
}

type UserLoginWxResp struct {
	CommonReply
	Token    string   `json:"token"`   // 访问令牌
	OpenId   string   `json:"open_id"` // 微信openid, 当错误码为9时返回
	UserInfo UserInfo `json:"data"`    // 用户信息
}

type UserRegisterReq struct {
	Account  string `json:"account"`  // 账号
	Password string `json:"password"` // 密码
	Name     string `json:"name"`     // 用户名
	Phone    string `json:"phone"`    // 手机号
	Email    string `json:"email"`    // 邮箱
}

type UserRegisterResp struct {
	CommonReply
}

type UserRegisterWxReq struct {
	OpenId string `json:"open_id"` // 微信openid
	Name   string `json:"name"`    // 用户名
	Avatar string `json:"avatar"`  // 头像
}

type UserRegisterWxResp struct {
	CommonReply
	Token    string   `json:"token"` // 访问令牌
	UserInfo UserInfo `json:"data"`  // 用户信息
}

type Word struct {
	ID         uint       `json:"id"`
	Word       string     `json:"word"`        // 单词
	UKPhonetic string     `json:"uk_phonetic"` // 英式音标
	UKAudio    string     `json:"uk_audio"`    // 英式音频
	USPhonetic string     `json:"us_phonetic"` // 美式音标
	USAudio    string     `json:"us_audio"`    // 美式音频
	Pos        []*WordPos `json:"pos"`         // 词性
}

type WordBriefItem struct {
	Word     string         `json:"word"`
	Type     int            `json:"type"`
	PosLabel string         `json:"pos_label"`
	Meaning  string         `json:"meaning"`
	Senses   []ArticleSense `json:"senses"`
	Phonetic string         `json:"phonetic"`
	Found    bool           `json:"found"`
}

type WordCard struct {
	ID               uint              `json:"id"`                // 词语ID
	Word             string            `json:"word"`              // 词语
	WordType         int               `json:"word_type"`         // 单词类型, 1-单词 2-短语
	UKPhonetic       string            `json:"uk_phonetic"`       // 英式音标
	UKAudio          string            `json:"uk_audio"`          // 英式音频
	USPhonetic       string            `json:"us_phonetic"`       // 美式音标
	USAudio          string            `json:"us_audio"`          // 美式音频
	Translation      string            `json:"translation"`       // 翻译(多行拼接, 兼容老前端)
	Example          []string          `json:"example"`           // 例句
	Picture          []string          `json:"picture"`           // 图片
	PicturePosIds    []uint            `json:"picture_pos_ids"`   // 图片对应ID (单词:word_pos_id, 短语:phrase_id)
	TranslationItems []TranslationItem `json:"translation_items"` // 拆分后的释义条目(用于编辑)
}

type WordPhrase struct {
	ID            uint       `json:"id"`            // 短语ID
	Phrase        string     `json:"phrase"`        // 短语
	Translation   string     `json:"translation"`   // 中文翻译
	Pronunciation string     `json:"pronunciation"` // 发音
	Example       []*Example `json:"example"`       // 例句
	Picture       string     `json:"picture"`       // 图片
}

type WordPos struct {
	ID          uint              `json:"id,optional"`          // 自定义的词性, id 从100W开始
	WordID      uint              `json:"word_id"`              // 单词ID
	Word        string            `json:"word,optional"`        // 单词
	Pos         int               `json:"pos,optional"`         // 词性
	Translation string            `json:"translation,optional"` // 中文翻译
	Example     []*Example        `json:"example,optional"`     // 例句, 一个元素是一个句子, 通过\n分割例句和中文翻译
	Picture     string            `json:"picture,optional"`     // 图片
	Exchange    map[string]string `json:"exchange,optional"`    // 变化形式, key是变化形式简写, value是变化形式的单词, 例如单词do, p:did, d:done, i:doing, 3:does
}

type WordStatus struct {
	ID       uint    `json:"id"`        // 单词状态ID
	WordID   uint    `json:"word_id"`   // 单词ID
	WordType int     `json:"word_type"` // 单词类型, 1-单词 2-短语
	Status   int     `json:"status"`    // 状态
	Times    int     `json:"times"`     // 学习次数
	Weight   float64 `json:"weight"`    // 权重
}

type WordTag struct {
	ID       uint   `json:"id"`        // 单词标签ID
	WordID   uint   `json:"word_id"`   // 单词ID
	WordType int    `json:"word_type"` // 单词类型, 1-单词 2-短语
	TagID    uint   `json:"tag_id"`    // 标签ID
	Name     string `json:"name"`      // 标签名称
	Style    string `json:"style"`     // 展示风格
}

type WordTextItem struct {
	Word string `json:"word"`
	Type int    `json:"type"` // 1-单词 2-短语
}

type WordsInfoReq struct {
	Words []WordTextItem `json:"words"`
}

type WordsInfoResp struct {
	CommonReply
	Data []*WordBriefItem `json:"data"`
}
