package eventbus

// Code generated by eventbus-gen. DO NOT EDIT.

import (
	resbus "github.com/NameOfGoy/resource-eventbus"
	"github.com/NameOfGoy/resource-eventbus/generator"
)

// eventWrapper 把业务 data 与 metadata 一起塞进底层 bus.
type eventWrapper[T any] struct {
	Data     T                        `json:"data"`
	Metadata *generator.EventMetadata `json:"metadata"`
}

// TypedEvent 与根包的 TypedEvent[T] 不同:
// 此版本把 EventMetadata 一并传递, 适合需要 source / trace_id 的场景.
type TypedEvent[T any] struct {
	topic string
}

func (e *TypedEvent[T]) Publish(data T, opts ...generator.EventOption) {
	resbus.GetBus().Publish(e.topic, eventWrapper[T]{
		Data:     data,
		Metadata: generator.NewEventMetadata(opts...),
	})
}

func (e *TypedEvent[T]) PublishAsync(data T, opts ...generator.EventOption) {
	go e.Publish(data, opts...)
}

func (e *TypedEvent[T]) Subscribe(handler func(T, *generator.EventMetadata)) error {
	return resbus.GetBus().Subscribe(e.topic, func(w eventWrapper[T]) {
		handler(w.Data, w.Metadata)
	})
}

func (e *TypedEvent[T]) SubscribeAsync(handler func(T, *generator.EventMetadata), transactional bool) error {
	return resbus.GetBus().SubscribeAsync(e.topic, func(w eventWrapper[T]) {
		handler(w.Data, w.Metadata)
	}, transactional)
}

func (e *TypedEvent[T]) SubscribeOnce(handler func(T, *generator.EventMetadata)) error {
	return resbus.GetBus().SubscribeOnce(e.topic, func(w eventWrapper[T]) {
		handler(w.Data, w.Metadata)
	})
}

func (e *TypedEvent[T]) SubscribeOnceAsync(handler func(T, *generator.EventMetadata)) error {
	return resbus.GetBus().SubscribeOnceAsync(e.topic, func(w eventWrapper[T]) {
		handler(w.Data, w.Metadata)
	})
}

func (e *TypedEvent[T]) HasCallback() bool {
	return resbus.GetBus().HasCallback(e.topic)
}

// TagEvents Tag事件集合
type TagEvents struct{}

// Tag 获取Tag事件集合
func Tag() *TagEvents { return &TagEvents{} }

func (e *TagEvents) Deleted() *TypedEvent[TagDeletedPayload] {
	return &TypedEvent[TagDeletedPayload]{topic: TagDeleted}
}
