// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"
	"time"

	article "english-study/internal/handler/article"
	cc "english-study/internal/handler/cc"
	dashboard "english-study/internal/handler/dashboard"
	dictionary "english-study/internal/handler/dictionary"
	file "english-study/internal/handler/file"
	practise "english-study/internal/handler/practise"
	share "english-study/internal/handler/share"
	tag "english-study/internal/handler/tag"
	user "english-study/internal/handler/user"
	"english-study/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 文章练习/即时生成(同步)
				Method:  http.MethodPost,
				Path:    "/generate",
				Handler: article.GenerateArticleHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/practise/article"),
		rest.WithTimeout(60000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 文章练习/自选候选词
				Method:  http.MethodGet,
				Path:    "/candidates",
				Handler: article.ArticleCandidatesHandler(serverCtx),
			},
			{
				// 文章练习/详情
				Method:  http.MethodGet,
				Path:    "/detail",
				Handler: article.ArticleDetailHandler(serverCtx),
			},
			{
				// 文章练习/收录列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: article.ListArticleHandler(serverCtx),
			},
			{
				// 文章练习/收录
				Method:  http.MethodPost,
				Path:    "/save",
				Handler: article.SaveArticleHandler(serverCtx),
			},
			{
				// 文章练习/词条简要批量
				Method:  http.MethodPost,
				Path:    "/words/info",
				Handler: article.WordsInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/practise/article"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// CC AI 桥/输 AccessKey 登录, 签发 access + refresh token (仅 admin)
				Method:  http.MethodPost,
				Path:    "/relay-login",
				Handler: cc.RelayLoginHandler(serverCtx),
			},
			{
				// CC AI 桥/用 refresh token 换新 access + 新 refresh (rotation: 旧 refresh 同步作废)
				Method:  http.MethodPost,
				Path:    "/relay-refresh",
				Handler: cc.RelayRefreshHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/cc"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 首页/今日学习看板
				Method:  http.MethodGet,
				Path:    "/",
				Handler: dashboard.GetDashboardHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/dashboard"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 字典模块/单词添加
				Method:  http.MethodPost,
				Path:    "/add",
				Handler: dictionary.AddWordHandler(serverCtx),
			},
			{
				// 字典模块/单词删除
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: dictionary.DeleteWordHandler(serverCtx),
			},
			{
				// 字典模块/单词详情
				Method:  http.MethodGet,
				Path:    "/detail",
				Handler: dictionary.GetWordDetailHandler(serverCtx),
			},
			{
				// 字典模块/例句生成
				Method:  http.MethodPost,
				Path:    "/example/generate",
				Handler: dictionary.GenerateExampleHandler(serverCtx),
			},
			{
				// 字典模块/例句更新
				Method:  http.MethodPost,
				Path:    "/example/update",
				Handler: dictionary.UpdateExampleHandler(serverCtx),
			},
			{
				// 字典模块/单词列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: dictionary.GetWordListHandler(serverCtx),
			},
			{
				// 字典模块/词性图片生成
				Method:  http.MethodPost,
				Path:    "/picture",
				Handler: dictionary.GenerateWordPictureHandler(serverCtx),
			},
			{
				// 字典模块/词性图片删除
				Method:  http.MethodPost,
				Path:    "/picture/delete",
				Handler: dictionary.DeleteWordPictureHandler(serverCtx),
			},
			{
				// 字典模块/词性图片更新
				Method:  http.MethodPost,
				Path:    "/picture/update",
				Handler: dictionary.UpdateWordPictureHandler(serverCtx),
			},
			{
				// 字典模块/批量更新单词释义
				Method:  http.MethodPost,
				Path:    "/translation/update",
				Handler: dictionary.UpdateWordTranslationHandler(serverCtx),
			},
			{
				// 字典模块/单词更新
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: dictionary.UpdateWordHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/dictionary/word"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 字典模块/添加短语
				Method:  http.MethodPost,
				Path:    "/add",
				Handler: dictionary.AddWordPhraseHandler(serverCtx),
			},
			{
				// 字典模块/删除短语
				Method:  http.MethodDelete,
				Path:    "/delete",
				Handler: dictionary.DeleteWordPhraseHandler(serverCtx),
			},
			{
				// 字典模块/获取短语详情
				Method:  http.MethodGet,
				Path:    "/detail",
				Handler: dictionary.GetWordPhraseDetailHandler(serverCtx),
			},
			{
				// 字典模块/例句生成
				Method:  http.MethodPost,
				Path:    "/example/generate",
				Handler: dictionary.GeneratePhraseExampleHandler(serverCtx),
			},
			{
				// 字典模块/例句更新
				Method:  http.MethodPost,
				Path:    "/example/update",
				Handler: dictionary.UpdatePhraseExampleHandler(serverCtx),
			},
			{
				// 字典模块/获取短语列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: dictionary.GetWordPhraseListHandler(serverCtx),
			},
			{
				// 字典模块/短语图片生成
				Method:  http.MethodPost,
				Path:    "/picture",
				Handler: dictionary.GeneratePhrasePictureHandler(serverCtx),
			},
			{
				// 字典模块/短语图片删除
				Method:  http.MethodPost,
				Path:    "/picture/delete",
				Handler: dictionary.DeletePhrasePictureHandler(serverCtx),
			},
			{
				// 字典模块/短语图片更新
				Method:  http.MethodPost,
				Path:    "/picture/update",
				Handler: dictionary.UpdatePhrasePictureHandler(serverCtx),
			},
			{
				// 字典模块/更新短语
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: dictionary.UpdateWordPhraseHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/dictionary/phrase"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 字典模块/获取单词状态列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: dictionary.GetWordStatusListHandler(serverCtx),
			},
			{
				// 字典模块/修改单词状态
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: dictionary.UpdateWordStatusHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/dictionary/status"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 字典模块/获取单词标签列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: dictionary.GetWordTagListHandler(serverCtx),
			},
			{
				// 字典模块/修改单词标签
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: dictionary.UpdateWordTagHandler(serverCtx),
			},
			{
				// 字典模块/按标签筛选词语(AND: 同时拥有全部所选标签)
				Method:  http.MethodGet,
				Path:    "/words",
				Handler: dictionary.ListWordsByTagsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/dictionary/tag"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 字典模块/批量导出
				Method:  http.MethodPost,
				Path:    "/export",
				Handler: dictionary.ExportWordHandler(serverCtx),
			},
			{
				// 字典模块/批量导入
				Method:  http.MethodPost,
				Path:    "/import",
				Handler: dictionary.ImportWordHandler(serverCtx),
			},
			{
				// 字典模块/导入任务列表
				Method:  http.MethodGet,
				Path:    "/import/tasks",
				Handler: dictionary.GetImportTaskListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/dictionary/operation"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 词典统计/词汇量
				Method:  http.MethodGet,
				Path:    "/count",
				Handler: dictionary.GetDictionaryCountHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/dictionary"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 词库搜索/批量添加到个人词典
				Method:  http.MethodPost,
				Path:    "/batch-add",
				Handler: dictionary.BatchAddStardictHandler(serverCtx),
			},
			{
				// 词库搜索/中文搜索stardict
				Method:  http.MethodGet,
				Path:    "/stardict",
				Handler: dictionary.SearchStardictHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/dictionary/search"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 文件模块/文件下载
				Method:  http.MethodGet,
				Path:    "/download",
				Handler: file.DownloadHandler(serverCtx),
			},
			{
				// 文件模块/搜索图片
				Method:  http.MethodGet,
				Path:    "/search-images",
				Handler: file.SearchImagesHandler(serverCtx),
			},
			{
				// 文件模块/文件上传
				Method:  http.MethodPost,
				Path:    "/upload",
				Handler: file.UploadHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/file-service"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 学习模式/完成学习
				Method:  http.MethodPost,
				Path:    "/finish",
				Handler: practise.FinishStudyHandler(serverCtx),
			},
			{
				// 学习模式/获取单词列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: practise.GetStudyWordCardListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/practise/study"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 复习模式/完成复习
				Method:  http.MethodPost,
				Path:    "/finish",
				Handler: practise.FinishReviewHandler(serverCtx),
			},
			{
				// 复习模式/获取单词列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: practise.GetReviewWordCardListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/practise/review"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 强化模式/完成强化
				Method:  http.MethodPost,
				Path:    "/finish",
				Handler: practise.FinishStrengthHandler(serverCtx),
			},
			{
				// 强化模式/获取单词列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: practise.GetStrengthWordCardListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/practise/strength"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 抽查模式/完成抽查
				Method:  http.MethodPost,
				Path:    "/finish",
				Handler: practise.FinishSpotHandler(serverCtx),
			},
			{
				// 抽查模式/获取单词列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: practise.GetSpotWordCardListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/practise/spot"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 分享/生成分享码
				Method:  http.MethodPost,
				Path:    "/generate",
				Handler: share.GenerateShareHandler(serverCtx),
			},
			{
				// 分享/导入分享码
				Method:  http.MethodPost,
				Path:    "/import",
				Handler: share.ImportShareHandler(serverCtx),
			},
			{
				// 分享/预览分享码内容
				Method:  http.MethodPost,
				Path:    "/preview",
				Handler: share.PreviewShareHandler(serverCtx),
			},
			{
				// 分享/获取分享中某个词的详情
				Method:  http.MethodPost,
				Path:    "/word-detail",
				Handler: share.GetShareWordDetailHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/share"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 标签模块/新增标签
				Method:  http.MethodPost,
				Path:    "/add",
				Handler: tag.AddTagHandler(serverCtx),
			},
			{
				// 标签模块/删除标签
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: tag.DeleteTagHandler(serverCtx),
			},
			{
				// 标签模块/获取标签详情
				Method:  http.MethodGet,
				Path:    "/detail",
				Handler: tag.GetTagDetailHandler(serverCtx),
			},
			{
				// 标签模块/获取标签列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: tag.GetTagListHandler(serverCtx),
			},
			{
				// 标签模块/更新标签
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: tag.UpdateTagHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/tag"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 用户模块/用户登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				// 用户模块/用户登录/微信登录
				Method:  http.MethodPost,
				Path:    "/login/wx",
				Handler: user.LoginWxHandler(serverCtx),
			},
			{
				// 用户模块/用户注册
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: user.RegisterHandler(serverCtx),
			},
			{
				// 用户模块/微信注册用户
				Method:  http.MethodPost,
				Path:    "/register/wx",
				Handler: user.RegisterWxHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 用户模块/获取用户信息
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: user.GetUserInfoHandler(serverCtx),
			},
			{
				// 用户模块/更新用户信息
				Method:  http.MethodPut,
				Path:    "/:id",
				Handler: user.UpdateUserInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/user"),
	)
}
