// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package errors

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 请求参数错误
func IsRequestParamError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorCode_REQUEST_PARAM_ERROR.String() && e.Code == 1
}

// 请求参数错误
func ErrorRequestParamError(format string, args ...interface{}) *errors.Error {
	return errors.New(1, ErrorCode_REQUEST_PARAM_ERROR.String(), fmt.Sprintf(format, args...))
}

// 数据库查询失败
func IsDatabaseQueryError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorCode_DATABASE_QUERY_ERROR.String() && e.Code == 2
}

// 数据库查询失败
func ErrorDatabaseQueryError(format string, args ...interface{}) *errors.Error {
	return errors.New(2, ErrorCode_DATABASE_QUERY_ERROR.String(), fmt.Sprintf(format, args...))
}

// 数据库更新失败
func IsDatabaseUpdateError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorCode_DATABASE_UPDATE_ERROR.String() && e.Code == 3
}

// 数据库更新失败
func ErrorDatabaseUpdateError(format string, args ...interface{}) *errors.Error {
	return errors.New(3, ErrorCode_DATABASE_UPDATE_ERROR.String(), fmt.Sprintf(format, args...))
}

// 数据库删除失败
func IsDatabaseDeleteError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorCode_DATABASE_DELETE_ERROR.String() && e.Code == 4
}

// 数据库删除失败
func ErrorDatabaseDeleteError(format string, args ...interface{}) *errors.Error {
	return errors.New(4, ErrorCode_DATABASE_DELETE_ERROR.String(), fmt.Sprintf(format, args...))
}

// 数据库插入失败
func IsDatabaseInsertError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorCode_DATABASE_INSERT_ERROR.String() && e.Code == 5
}

// 数据库插入失败
func ErrorDatabaseInsertError(format string, args ...interface{}) *errors.Error {
	return errors.New(5, ErrorCode_DATABASE_INSERT_ERROR.String(), fmt.Sprintf(format, args...))
}

// token 生成失败
func IsTokenGenerateError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorCode_TOKEN_GENERATE_ERROR.String() && e.Code == 6
}

// token 生成失败
func ErrorTokenGenerateError(format string, args ...interface{}) *errors.Error {
	return errors.New(6, ErrorCode_TOKEN_GENERATE_ERROR.String(), fmt.Sprintf(format, args...))
}

// token 解析失败
func IsTokenParseError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorCode_TOKEN_PARSE_ERROR.String() && e.Code == 7
}

// token 解析失败
func ErrorTokenParseError(format string, args ...interface{}) *errors.Error {
	return errors.New(7, ErrorCode_TOKEN_PARSE_ERROR.String(), fmt.Sprintf(format, args...))
}

// 账号已存在
func IsAccountExistError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorCode_ACCOUNT_EXIST_ERROR.String() && e.Code == 8
}

// 账号已存在
func ErrorAccountExistError(format string, args ...interface{}) *errors.Error {
	return errors.New(8, ErrorCode_ACCOUNT_EXIST_ERROR.String(), fmt.Sprintf(format, args...))
}

// 账号不存在
func IsAccountNotExistError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorCode_ACCOUNT_NOT_EXIST_ERROR.String() && e.Code == 9
}

// 账号不存在
func ErrorAccountNotExistError(format string, args ...interface{}) *errors.Error {
	return errors.New(9, ErrorCode_ACCOUNT_NOT_EXIST_ERROR.String(), fmt.Sprintf(format, args...))
}

// 权限错误
func IsPermissionError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorCode_PERMISSION_ERROR.String() && e.Code == 10
}

// 权限错误
func ErrorPermissionError(format string, args ...interface{}) *errors.Error {
	return errors.New(10, ErrorCode_PERMISSION_ERROR.String(), fmt.Sprintf(format, args...))
}

// 数据上传失败
func IsDataUploadError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorCode_DATA_UPLOAD_ERROR.String() && e.Code == 11
}

// 数据上传失败
func ErrorDataUploadError(format string, args ...interface{}) *errors.Error {
	return errors.New(11, ErrorCode_DATA_UPLOAD_ERROR.String(), fmt.Sprintf(format, args...))
}

// 数据下载失败
func IsDataDownloadError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorCode_DATA_DOWNLOAD_ERROR.String() && e.Code == 12
}

// 数据下载失败
func ErrorDataDownloadError(format string, args ...interface{}) *errors.Error {
	return errors.New(12, ErrorCode_DATA_DOWNLOAD_ERROR.String(), fmt.Sprintf(format, args...))
}

// 微信鉴权失败
func IsWxAuthError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorCode_WX_AUTH_ERROR.String() && e.Code == 13
}

// 微信鉴权失败
func ErrorWxAuthError(format string, args ...interface{}) *errors.Error {
	return errors.New(13, ErrorCode_WX_AUTH_ERROR.String(), fmt.Sprintf(format, args...))
}

// 微信获取用户信息失败
func IsWxGetUserInfoError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorCode_WX_GET_USER_INFO_ERROR.String() && e.Code == 14
}

// 微信获取用户信息失败
func ErrorWxGetUserInfoError(format string, args ...interface{}) *errors.Error {
	return errors.New(14, ErrorCode_WX_GET_USER_INFO_ERROR.String(), fmt.Sprintf(format, args...))
}

// 单词不存在
func IsWordNotExistError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorCode_WORD_NOT_EXIST_ERROR.String() && e.Code == 15
}

// 单词不存在
func ErrorWordNotExistError(format string, args ...interface{}) *errors.Error {
	return errors.New(15, ErrorCode_WORD_NOT_EXIST_ERROR.String(), fmt.Sprintf(format, args...))
}

// 不支持的操作
func IsNotSupportError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorCode_NOT_SUPPORT_ERROR.String() && e.Code == 16
}

// 不支持的操作
func ErrorNotSupportError(format string, args ...interface{}) *errors.Error {
	return errors.New(16, ErrorCode_NOT_SUPPORT_ERROR.String(), fmt.Sprintf(format, args...))
}

// 资源生成失败
func IsResourceGenerateError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorCode_RESOURCE_GENERATE_ERROR.String() && e.Code == 17
}

// 资源生成失败
func ErrorResourceGenerateError(format string, args ...interface{}) *errors.Error {
	return errors.New(17, ErrorCode_RESOURCE_GENERATE_ERROR.String(), fmt.Sprintf(format, args...))
}
